const fs=require('fs');const vm=require('vm');const assert=require('assert');
class Repo{constructor(){this.rows=[]}list(){return this.rows.map(x=>({...x}))}upsert(row){const i=this.rows.findIndex(x=>String(x.id)===String(row.id));if(i>=0)this.rows[i]={...this.rows[i],...row};else this.rows.unshift({...row});return {...this.rows.find(x=>String(x.id)===String(row.id))}}}
const customers=new Repo(),products=new Repo(),deals=new Repo(),mail=new Repo();products.rows=[{id:'p1',name:'Stainless Steel Hinge',sku:'HINGE-01',category:'hardware',spec:'304 stainless steel'},{id:'p2',name:'Door Handle',sku:'HANDLE-02',category:'hardware',spec:'zinc alloy'}];
let contextArgs=null,emitted=null;global.window={HUIDILocalCore:{repositories:{customers,products,deals,mail},context:{create(args){contextArgs=args}},emit(topic,payload){emitted={topic,payload}}}};global.document={querySelectorAll(){return[]}};global.location={hash:'',href:'',pathname:'/online-bridge.html'};const store={};global.sessionStorage={setItem(k,v){store[k]=v},getItem(k){return store[k]||null}};
const source=fs.readFileSync('../../public/huidi-online-local-bridge-v1.js','utf8');vm.runInThisContext(source,{filename:'huidi-online-local-bridge-v1.js'});const bridge=window.HUIDIOnlineLocalBridge;assert(bridge,'bridge must initialize');
const bundle={schema:'huidi.business.bundle/v1',generated_at:new Date().toISOString(),source:'HUIDI Docs Online',source_lead_id:'88',lead:{priority:'A',score:86,reason:'产品匹配 · 买家角色信号',market_keyword:'stainless steel hinge',assessment:{confidence:82,readiness:'ready_to_contact',dimensions:{basic:90,company:80,contact:75,digital:80,trade:0,fit:86},report:{trade_status:'unverified',gaps:['海关未验证']}}},customer:{company:'Acme Import GmbH',contact:'Anna',email:'anna@acme.example',country:'Germany',website:'https://acme.example',currency:'EUR',preferred_language:'English',tags:'Online线索 A级'},deal:{title:'Acme Import GmbH · stainless steel hinge',stage:'new_inquiry',currency:'EUR',product_keyword:'stainless steel hinge',requirements:'Need hinge supplier',next_action:'准备报价',next_action_at:'2026-09-10'},mail_draft:{to:'anna@acme.example',subject:'Hinge cooperation',body:'Dear Anna...',language:'English',approved:true},activity:[{event_type:'followup_scheduled',payload:{due_at:'2026-09-10T09:00:00'}}]};
const preview=bridge.preview(bundle);assert.strictEqual(preview.ok,true);assert(preview.matchedProducts.some(x=>x.id==='p1'),'matching must find existing Local product');
const first=bridge.importBundle(bundle,{productIds:['p1']});assert.strictEqual(customers.rows.length,1);assert.strictEqual(deals.rows.length,1);assert.strictEqual(mail.rows.length,1);assert.strictEqual(first.deal.customer_id,first.customer.id);assert.deepStrictEqual(first.deal.product_ids,['p1']);assert.strictEqual(first.deal.probability,20,'Online lead score must not become deal probability');assert.strictEqual(first.deal.online_lead_score,86);assert.strictEqual(first.customer.online_source_lead_id,'88');assert.strictEqual(first.mail.deal_id,first.deal.id);assert.strictEqual(first.mail.draft_approved,true);assert.strictEqual(emitted.topic,'online.bridge.imported');
const second=bridge.importBundle({...bundle,customer:{...bundle.customer,contact:'Anna Meyer'}},{productIds:['p1']});assert.strictEqual(customers.rows.length,1,'re-import must dedupe customer');assert.strictEqual(deals.rows.length,1,'re-import must dedupe deal');assert.strictEqual(mail.rows.length,1,'re-import must dedupe mail draft');assert.strictEqual(second.customer.id,first.customer.id);assert.strictEqual(second.deal.id,first.deal.id);assert.strictEqual(customers.rows[0].contact,'Anna Meyer');
bridge.openDocument('quotation',second);assert.strictEqual(contextArgs.type,'quotation');assert.strictEqual(contextArgs.dealId,second.deal.id);assert.strictEqual(contextArgs.customerId,second.customer.id);assert.deepStrictEqual(contextArgs.productIds,['p1']);assert(location.href.includes('editor.html?type=quotation'));
location.href='';bridge.openCatalog(second);const catalog=JSON.parse(store.flypigbox_catalog_product_ids_v1);assert.strictEqual(catalog.dealId,second.deal.id);assert.deepStrictEqual(catalog.ids,['p1']);assert.strictEqual(location.href,'./catalog-studio/index.html');
console.log('HUIDI Online ↔ Local bridge contract PASS');
