(()=>{'use strict';
let leads=[],current=null,currentActivities=[],status='',page=1,pageSize=50,total=0,pages=1;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const clean=v=>String(v??'').trim();
const clamp=(v,n=500)=>clean(v).slice(0,n);
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});if(!r.ok)throw new Error(await r.text()||r.statusText);return r.json()}
function stateName(s){return({new:'新客户',qualified:'已筛选',contacted:'已联系',replied:'已回复',converted:'已转询盘',archived:'归档'})[s]||s}
function readinessName(s){return({ready_to_contact:'可进入联系',verify_then_contact:'建议补核后联系',insufficient:'信息不足'})[s]||s}
async function health(){try{const h=await api('/api/health');$('#health').textContent=(h.search_provider==='serper'?'在线找客户已连接':'在线找客户未连接')+' · V'+h.version}catch{$('#health').textContent='服务异常'}}
function ensurePager(){let el=$('#leadPager');if(el)return el;const table=$('#tbody')?.closest('table');if(!table)return null;el=document.createElement('div');el.id='leadPager';el.style.cssText='display:flex;align-items:center;justify-content:space-between;gap:10px;padding:12px 2px 2px;font-size:12px;color:#667085;flex-wrap:wrap';table.insertAdjacentElement('afterend',el);el.addEventListener('click',e=>{if(e.target.closest('[data-lead-prev]')&&page>1){page--;load()}if(e.target.closest('[data-lead-next]')&&page<pages){page++;load()}});el.addEventListener('change',e=>{if(e.target.matches('[data-lead-size]')){pageSize=Number(e.target.value)||50;page=1;load()}});return el}
function renderPager(){const el=ensurePager();if(!el)return;el.innerHTML=`<span>共 <b>${total}</b> 条 · 每页 <select data-lead-size style="height:32px;border:1px solid #d8e2ef;border-radius:8px;padding:0 7px;background:#fff">${[20,50,100,200].map(n=>`<option value="${n}" ${n===pageSize?'selected':''}>${n}</option>`).join('')}</select></span><span style="display:flex;align-items:center;gap:8px"><button class="action" data-lead-prev ${page<=1?'disabled':''}>‹ 上一页</button><b>${page} / ${pages}</b><button class="action" data-lead-next ${page>=pages?'disabled':''}>下一页 ›</button></span>`}
function render(){const rows=leads;$('#meta').textContent=`${total} 条潜在客户 · 第 ${page}/${pages} 页`;$('#empty').style.display=rows.length?'none':'block';$('#tbody').innerHTML=rows.map(x=>`<tr><td><span class="priority ${esc(x.priority)}">${esc(x.priority)}</span></td><td><div class="company">${esc(x.company_name)}</div><div class="sub"><a href="${esc(x.website)}" target="_blank" rel="noreferrer">${esc(x.domain)}</a></div></td><td>${esc(x.country||'—')}</td><td><span class="score ${x.score>=78?'high':x.score>=62?'mid':''}">${Math.round(x.score)}</span></td><td class="reason">${esc(x.reason)}</td><td>${esc(x.contact_name||x.contact_role||'—')}</td><td>${esc(x.contact_email||'—')}</td><td>${x.assessment?`<span class="badge">${Math.round(x.assessment.confidence)} · ${readinessName(x.assessment.readiness)}</span>`:'—'}</td><td><span class="badge">${stateName(x.status)}</span></td><td><button class="action" data-open="${x.id}">查看</button><button class="action" data-qualify="${x.id}">筛选</button></td></tr>`).join('');renderPager()}
async function load(){const qs=new URLSearchParams({paged:'1',page:String(page),page_size:String(pageSize)});if(status)qs.set('status',status);const data=await api('/api/leads?'+qs.toString());if(Array.isArray(data)){const filtered=data.filter(x=>!status||x.status===status);total=filtered.length;pages=Math.max(1,Math.ceil(total/pageSize));page=Math.min(page,pages);leads=filtered.slice((page-1)*pageSize,page*pageSize)}else{leads=Array.isArray(data.items)?data.items:[];total=Number(data.total||0);page=Number(data.page||page||1);pageSize=Number(data.page_size||pageSize||50);pages=Math.max(1,Number(data.pages||Math.ceil(total/pageSize)||1))}render()}
function renderAssessment(a){if(!a){$('#assessmentBox').innerHTML='尚未进行背调初筛。';return}const r=a.report||{},d=a.dimensions||{},pos=(r.positives||[]).map(x=>`<li class="ok">✓ ${esc(x)}</li>`).join(''),gaps=(r.gaps||[]).map(x=>`<li class="gap">○ ${esc(x)}</li>`).join('');$('#assessmentBox').innerHTML=`<div class="assessment-head"><div><div class="confidence">${Math.round(a.confidence)}</div><div class="muted">当前证据置信度 / 100</div></div><span class="readiness">${readinessName(a.readiness)}</span></div><div class="meter-grid"><div class="meter"><small>基础资料</small><b>${Math.round(d.basic||0)}</b></div><div class="meter"><small>公司存在信号</small><b>${Math.round(d.company||0)}</b></div><div class="meter"><small>联系人</small><b>${Math.round(d.contact||0)}</b></div><div class="meter"><small>数字资产</small><b>${Math.round(d.digital||0)}</b></div><div class="meter"><small>业务匹配</small><b>${Math.round(d.fit||0)}</b></div><div class="meter"><small>海关/贸易</small><b>${r.trade_status==='unverified'?'未验证':Math.round(d.trade||0)}</b></div></div><ul class="check-list">${pos}${gaps}</ul><div class="warning">${esc(r.disclaimer||'')}</div>`}
async function loadTimeline(){if(!current)return;currentActivities=await api(`/api/leads/${current.id}/activities`);$('#timeline').innerHTML=currentActivities.length?currentActivities.map(x=>`<div class="event"><div class="event-dot"></div><div><div class="event-title">${esc(x.title)}</div><div class="event-meta">${esc((x.created_at||'').replace('T',' ').slice(0,16))}</div>${x.detail?`<div class="event-detail">${esc(x.detail)}</div>`:''}</div></div>`).join(''):'<div class="muted">暂无记录。</div>'}
async function openLead(id){current=leads.find(x=>String(x.id)===String(id));if(!current){const all=await api('/api/leads');current=Array.isArray(all)?all.find(x=>String(x.id)===String(id)):null}if(!current)return;$('#dCompany').textContent=current.company_name;$('#dWebsite').innerHTML=`${esc(current.country||'')} · 优先级 ${esc(current.priority)} · 匹配分 ${Math.round(current.score)} · <a href="${esc(current.website)}" target="_blank" rel="noreferrer">${esc(current.domain)}</a><br>${esc(current.reason)}`;$('#dContact').value=current.contact_name||'';$('#dRole').value=current.contact_role||'';$('#dEmail').value=current.contact_email||'';$('#dStatus').value=current.status;$('#productSummary').value=current.market_keyword||'';$('#draftBox').textContent=current.draft_subject?current.draft_subject+'\n\n'+current.draft_body:'还没有生成开发信。';renderAssessment(current.assessment);$('#approveDraft').classList.remove('approved');$('#backdrop').classList.add('open');await loadTimeline();updateBridgeStatus();window.HUIDICustomerIntelligence?.loadCustomer?.(current.id,false)}
function latestFollowup(){const hit=currentActivities.find(x=>x.event_type==='followup_scheduled'&&clean(x.payload?.due_at));return clean(hit?.payload?.due_at)}
function approvedDraft(){return currentActivities.some(x=>x.event_type==='draft_approved')&&!currentActivities.some(x=>x.event_type==='draft_rejected'&&new Date(x.created_at||0)>new Date(currentActivities.find(y=>y.event_type==='draft_approved')?.created_at||0))}
function compactEvidence(rows){return (Array.isArray(rows)?rows:[]).slice(0,8).map(x=>({title:clamp(x.title,180),url:clamp(x.url,500),snippet:clamp(x.snippet,450),source:clamp(x.source,60)}))}
function compactActivities(rows){return (Array.isArray(rows)?rows:[]).slice(0,20).map(x=>({event_type:clamp(x.event_type,80),title:clamp(x.title,160),detail:clamp(x.detail,300),created_at:x.created_at||'',payload:x.event_type==='followup_scheduled'?{due_at:clamp(x.payload?.due_at,80)}:{}}))}
function makeBundle(){if(!current)throw new Error('没有选中客户');const follow=latestFollowup();const language=$('#draftLang').value||'English';return{schema:'huidi.business.bundle/v1',generated_at:new Date().toISOString(),source:'HUIDI Docs Online',source_lead_id:String(current.id),lead:{priority:current.priority,score:Number(current.score||0),reason:clamp(current.reason,1000),country:current.country||'',buyer_type:current.buyer_type||'',market_keyword:current.market_keyword||'',website:current.website||'',evidence:compactEvidence(current.evidence),assessment:current.assessment||null},customer:{company:current.company_name||'',contact:current.contact_name||'',email:current.contact_email||'',phone:'',country:current.country||'',website:current.website||'',currency:'USD',preferred_language:language,tags:`Online潜在客户 ${current.priority||'未分级'}级`,notes:`来源：HUIDI Online\n匹配：${current.reason||'—'}`},deal:{title:`${current.company_name||'客户'} · ${current.market_keyword||'新询盘'}`,stage:'new_inquiry',currency:'USD',product_keyword:current.market_keyword||'',requirements:current.reason||'',next_action:current.draft_body?'确认开发信 / 等待客户回复':'核对需求并准备开发',next_action_at:follow,notes:`Online客户 #${current.id} · ${current.priority||'—'} · ${Math.round(current.score||0)}分`},mail_draft:current.draft_subject||current.draft_body?{to:current.contact_email||'',subject:current.draft_subject||'',body:current.draft_body||'',language,approved:approvedDraft()}:null,activity:compactActivities(currentActivities),recommended_document:'quotation'}}
function encodeBundle(bundle){const bytes=new TextEncoder().encode(JSON.stringify(bundle));let binary='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)binary+=String.fromCharCode(...bytes.subarray(i,i+chunk));return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function localBase(){let value=clean($('#localBase').value)||'http://127.0.0.1:8765';if(!/^https?:\/\/(127\.0\.0\.1|localhost)(:\d{1,5})?$/i.test(value))throw new Error('本地地址只允许 127.0.0.1 或 localhost，例如 http://127.0.0.1:8765');return value.replace(/\/$/,'')}
function updateBridgeStatus(){const base=localStorage.getItem('huidi_local_bridge_base_v1')||'http://127.0.0.1:8765';$('#localBase').value=base;$('#bridgeStatus').textContent=current?`将同步：${current.company_name} → 客户中心 + 新询盘${current.draft_body?' + 邮件草稿':''}。产品会在本机按关键词重新匹配。`:'选择客户后可同步。'}
async function syncToLocal(){if(!current)return;let popup=null;try{const base=localBase();localStorage.setItem('huidi_local_bridge_base_v1',base);popup=window.open('about:blank','_blank');const id=current.id;await api(`/api/leads/${id}/convert`,{method:'POST',body:JSON.stringify({inquiry_title:`${current.company_name} · ${current.market_keyword||'新询盘'}`})});const bundle=makeBundle();const encoded=encodeBundle(bundle);if(encoded.length>110000)throw new Error('同步数据过大，请减少客户证据后重试。');const url=`${base}/online-bridge.html#bundle=${encoded}`;if(popup){popup.location.href=url}else{location.href=url}await load();current=leads.find(x=>String(x.id)===String(id))||current;await loadTimeline()}catch(e){try{popup?.close()}catch(_){}alert('同步失败：'+(e.message||e))}}
document.addEventListener('click',async e=>{const open=e.target.closest('[data-open]');if(open){await openLead(open.dataset.open);return}const q=e.target.closest('[data-qualify]');if(q){await api('/api/leads/'+q.dataset.qualify,{method:'PATCH',body:JSON.stringify({status:'qualified'})});await load();return}});
$('#closeDrawer').onclick=()=>$('#backdrop').classList.remove('open');$('#backdrop').onclick=e=>{if(e.target===$('#backdrop'))$('#backdrop').classList.remove('open')};
$('#tabs').onclick=e=>{if(!e.target.matches('.tab'))return;document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');status=e.target.dataset.status;page=1;load()};
$('#searchBtn').onclick=async()=>{const k=$('#keyword').value.trim();if(!k)return alert('先填写产品 / 行业关键词');$('#searchBtn').disabled=true;$('#searchBtn').textContent='搜索中…';try{const r=await api('/api/leads/search',{method:'POST',body:JSON.stringify({product_keyword:k,country:$('#country').value.trim(),buyer_type:$('#buyerType').value.trim(),limit:12})});page=1;await load();if(r.mode==='demo')alert('当前还没有连接在线找客户服务，没有可用的真实搜索结果。请先在“数据来源”中连接后再搜索。')}catch(e){alert('搜索失败：'+e.message)}finally{$('#searchBtn').disabled=false;$('#searchBtn').textContent='开始找客户'}};
$('#saveLead').onclick=async()=>{if(!current)return;const id=current.id;await api('/api/leads/'+id,{method:'PATCH',body:JSON.stringify({contact_name:$('#dContact').value,contact_role:$('#dRole').value,contact_email:$('#dEmail').value,status:$('#dStatus').value})});await load();await openLead(id)};
$('#findContact').onclick=async()=>{if(!current)return;const id=current.id;try{const r=await api(`/api/leads/${id}/find-contact`,{method:'POST'});if(r.mode==='demo')alert('当前还没有连接公开联系人搜索服务。');await load();await openLead(id)}catch(e){alert(e.message)}};
$('#assessLead').onclick=async()=>{if(!current)return;const id=current.id;try{await api(`/api/leads/${id}/assess`,{method:'POST'});await load();await openLead(id)}catch(e){alert(e.message)}};
$('#makeDraft').onclick=async()=>{if(!current)return;const id=current.id;try{await api(`/api/leads/${id}/draft`,{method:'POST',body:JSON.stringify({language:$('#draftLang').value,product_summary:$('#productSummary').value})});await load();await openLead(id)}catch(e){alert(e.message)}};
$('#approveDraft').onclick=async()=>{if(!current)return;try{await api(`/api/leads/${current.id}/draft-approval`,{method:'POST',body:JSON.stringify({approved:true})});$('#approveDraft').classList.add('approved');await loadTimeline();updateBridgeStatus()}catch(e){alert(e.message)}};
$('#rejectDraft').onclick=async()=>{if(!current)return;const note=prompt('需要修改什么？','补充客户场景或缩短内容');if(note===null)return;await api(`/api/leads/${current.id}/draft-approval`,{method:'POST',body:JSON.stringify({approved:false,note})});await loadTimeline();updateBridgeStatus()};
$('#saveFollow').onclick=async()=>{if(!current)return;const due=$('#followAt').value;if(!due)return alert('先选择跟进时间');await api(`/api/leads/${current.id}/followup`,{method:'POST',body:JSON.stringify({due_at:due,note:$('#followNote').value})});$('#followNote').value='';await loadTimeline();updateBridgeStatus()};
$('#syncLocal').onclick=syncToLocal;$('#saveLocalBase').onclick=()=>{try{const base=localBase();localStorage.setItem('huidi_local_bridge_base_v1',base);$('#bridgeStatus').textContent=`已记住本地地址：${base}`;}catch(e){alert(e.message)}};
window.HUIDILeadWorkbench={open:openLead,refresh:load,refreshTimeline:loadTimeline,current:()=>current};
window.openLead=openLead;
health();load();updateBridgeStatus();
})();