(()=>{'use strict';
if(window.HUIDIAuditUI)return;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let category='';
const friendly=e=>window.HUIDIPlainLanguage?.message?.(e?.message||e)||String(e?.message||e||'暂时无法读取操作记录');
async function api(url){const r=await fetch(url);if(!r.ok){let m=await r.text();try{m=JSON.parse(m).detail||m}catch(_){}throw new Error(m||r.statusText)}return r.json()}
function css(){if($('#auCss'))return;const s=document.createElement('style');s.id='auCss';s.textContent=`.au-back{position:fixed;inset:0;background:rgba(15,27,45,.38);z-index:188;display:none;justify-content:flex-end}.au-back.open{display:flex}.au-panel{width:min(720px,94vw);height:100%;background:#fff;box-shadow:-24px 0 70px rgba(20,38,61,.18);display:flex;flex-direction:column}.au-head{padding:18px 20px 12px;border-bottom:1px solid #e5eaf0}.au-headtop{display:flex;align-items:center;justify-content:space-between;gap:12px}.au-head h2{font-size:18px;margin:0;color:#273c55}.au-head p{font-size:10px;color:#738195;margin:5px 0 0;line-height:1.55}.au-close{border:0;background:#f1f4f7;border-radius:9px;width:32px;height:32px;font-size:18px;cursor:pointer}.au-stats{display:flex;gap:8px;margin-top:12px;flex-wrap:wrap}.au-stat{border:1px solid #e1e7ee;border-radius:10px;padding:8px 10px;min-width:100px}.au-stat b{display:block;font-size:15px;color:#2d4766}.au-stat span{font-size:8.5px;color:#7a8798}.au-filters{display:flex;gap:6px;padding:10px 20px;border-bottom:1px solid #edf0f4;overflow:auto}.au-filter{border:1px solid #dce4ed;background:#fff;border-radius:999px;padding:6px 9px;font-size:9px;color:#52657b;white-space:nowrap;cursor:pointer}.au-filter.active{background:#eef4ff;border-color:#bed1f5;color:#2457aa}.au-list{padding:8px 20px 24px;overflow:auto;display:grid;gap:7px}.au-item{border:1px solid #e4e9ef;border-radius:11px;padding:10px 11px;display:grid;grid-template-columns:1fr auto;gap:5px 10px}.au-main b{font-size:10px;color:#314b68}.au-main span{font-size:8.5px;color:#748397;margin-left:6px}.au-meta{font-size:8.5px;color:#7c8999;margin-top:4px}.au-ok,.au-fail{font-size:8px;border-radius:999px;padding:4px 6px;align-self:start}.au-ok{background:#edf7f1;color:#287a4b}.au-fail{background:#fff0f0;color:#b24a4a}.au-empty{padding:28px;text-align:center;color:#7c8999;font-size:10px}.au-more{margin:3px auto 0;border:1px solid #dce4ed;background:#fff;border-radius:9px;padding:7px 12px;font-size:9px;cursor:pointer}`;document.head.appendChild(s)}
function shell(){if($('#auBack'))return;const d=document.createElement('div');d.id='auBack';d.className='au-back';d.innerHTML='<aside class="au-panel"><div class="au-head"><div class="au-headtop"><div><h2>操作记录</h2><p id="auHint">查看最近谁处理了客户、邮件、询盘、产品和团队设置。</p></div><button class="au-close" data-au-close>×</button></div><div class="au-stats" id="auStats"></div></div><div class="au-filters" id="auFilters"></div><div class="au-list" id="auList"></div></aside>';document.body.appendChild(d);d.querySelector('[data-au-close]').onclick=()=>d.classList.remove('open');d.onclick=e=>{if(e.target===d)d.classList.remove('open')}}
const cats=[['','全部'],['customer','客户'],['lead','潜在客户'],['mail','邮件'],['followup','跟进'],['business','询盘'],['product','产品'],['intelligence','联网资料'],['team','团队']];
function filters(){const box=$('#auFilters');box.innerHTML=cats.map(([v,n])=>`<button class="au-filter${v===category?' active':''}" data-au-cat="${v}">${n}</button>`).join('');box.querySelectorAll('[data-au-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.auCat||'';filters();load()})}
function dt(v){if(!v)return'';try{return new Date(v).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}catch(_){return v}}
function role(v){return ({owner:'老板',admin:'管理员',sales:'业务员',viewer:'只读成员',system:'系统'})[v]||''}
function resource(x){const map={lead:'潜在客户',customer:'客户',deal:'询盘',mail:'邮件',mailbox:'邮箱',sequence:'自动跟进',product:'产品',member:'成员',organization:'公司',team:'团队',business:'业务'};return map[x.resource_type]||''}
function actionName(v){return ({'修改数据服务接入方式':'修改数据来源特殊要求','修改数据服务':'修改数据来源','检查数据服务':'检查数据来源','加入待发送':'加入待发送','确认单据业务参考':'确认单据参考'})[v]||v||'操作'}
async function load(before=''){const list=$('#auList');if(!before)list.innerHTML='<div class="au-empty">正在读取…</div>';try{const q=new URLSearchParams({limit:'80'});if(category)q.set('category',category);if(before)q.set('before_id',before);const [out,sum]=await Promise.all([api('/api/audit/records?'+q),api('/api/audit/summary')]);$('#auHint').textContent=out.team_view?'老板和管理员可查看当前公司的团队操作；普通成员只看自己的。':'这里只显示你自己的操作记录。';$('#auStats').innerHTML=`<div class="au-stat"><b>${sum.last_24h||0}</b><span>最近 24 小时</span></div><div class="au-stat"><b>${sum.failed||0}</b><span>未成功</span></div>${sum.actors?.slice(0,3).map(a=>`<div class="au-stat"><b>${a.count}</b><span>${esc(a.name)}</span></div>`).join('')||''}`;const html=(out.items||[]).map(x=>`<div class="au-item"><div class="au-main"><b>${esc(actionName(x.action))}</b><span>${esc(x.actor_name||'系统')}${x.actor_role?` · ${esc(role(x.actor_role))}`:''}</span><div class="au-meta">${esc(dt(x.created_at))}${resource(x)?` · ${esc(resource(x))}`:''}</div></div><span class="${x.success?'au-ok':'au-fail'}">${x.success?'已完成':'未成功'}</span></div>`).join('');if(before)list.insertAdjacentHTML('beforeend',html);else list.innerHTML=html||'<div class="au-empty">还没有操作记录。</div>';list.querySelector('[data-au-more]')?.remove();if(out.next_before_id)list.insertAdjacentHTML('beforeend',`<button class="au-more" data-au-more="${out.next_before_id}">查看更多</button>`);list.querySelector('[data-au-more]')?.addEventListener('click',e=>{const id=e.currentTarget.dataset.auMore;e.currentTarget.remove();load(id)})}catch(e){if(!before)list.innerHTML=`<div class="au-empty">${esc(friendly(e))}</div>`}}
function open(){css();shell();filters();$('#auBack').classList.add('open');load()}
function boot(){css();shell();document.querySelectorAll('[data-huidi-audit]').forEach(x=>x.addEventListener('click',open))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.HUIDIAuditUI=Object.freeze({open});
})();