(()=>{'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
let status={enabled:true,signup_enabled:true,providers:{email:true,phone:false,wechat:false,feishu:false},password_reset_email:false},mode='email';
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let body=null;try{body=await r.json()}catch(_){body={detail:await r.text()}}if(!r.ok)throw new Error(body?.detail||body?.message||r.statusText);return body}
function pathMode(){const p=location.pathname;if(p==='/register')return'register';if(p==='/forgot-password')return'forgot';if(p==='/reset-password')return'reset';return'login'}
function note(text,type=''){const el=$('#authMsg');if(!el)return;el.className='auth-note'+(type?` ${type}`:'');el.textContent=text||'';el.classList.toggle('auth-hidden',!text)}
function busy(btn,on,text='处理中…'){if(!btn)return;btn.disabled=!!on;if(on){btn.dataset.oldText=btn.textContent;btn.textContent=text}else if(btn.dataset.oldText){btn.textContent=btn.dataset.oldText;delete btn.dataset.oldText}}
function providerButtons(){const p=status.providers||{};return `<div class="auth-divider">其他登录方式</div><div class="auth-providers"><button class="auth-provider" data-oauth="wechat" ${p.wechat?'':'disabled'}>微信扫码登录${p.wechat?'':' · 未配置'}</button><button class="auth-provider" data-oauth="feishu" ${p.feishu?'':'disabled'}>飞书登录${p.feishu?'':' · 未配置'}</button></div>`}
function loginHtml(){const phone=!!status.providers?.phone;return `<div class="auth-head"><h2>登录 HUIDI</h2><p>进入你自己的客户、询盘、邮件、产品和单据工作区。</p></div><div class="auth-tabs"><button class="auth-tab ${mode==='email'?'active':''}" data-login-tab="email">邮箱登录</button><button class="auth-tab ${mode==='phone'?'active':''}" data-login-tab="phone" ${phone?'':'disabled'}>手机号登录</button></div><div id="authLoginBody">${mode==='phone'?phoneLoginFields():emailLoginFields()}</div>${providerButtons()}<div id="authMsg" class="auth-note auth-hidden"></div><div class="auth-foot"><span>还没有账号？</span><a class="auth-link" href="/register">注册独立工作区</a><span class="auth-spacer"></span><a class="auth-link muted" href="/forgot-password">忘记密码</a></div><div class="auth-security">登录成功后，服务器按工作区隔离业务数据库；不会把其他个人或团队的数据混到当前账号。</div>`}
function emailLoginFields(){return `<form id="emailLoginForm"><div class="auth-field"><label>邮箱</label><input id="loginEmail" type="email" autocomplete="username" placeholder="name@company.com"></div><div class="auth-field"><label>密码</label><input id="loginPassword" type="password" autocomplete="current-password" placeholder="至少 8 位"></div><div class="auth-row"><button class="auth-primary" id="loginBtn" type="submit">登录</button></div></form>`}
function phoneLoginFields(){return `<form id="phoneLoginForm"><div class="auth-field"><label>手机号</label><input id="loginPhone" inputmode="tel" autocomplete="tel" placeholder="+8613812345678"></div><div class="auth-field"><label>验证码</label><div class="auth-code"><input id="phoneCode" inputmode="numeric" autocomplete="one-time-code" placeholder="6 位验证码"><button type="button" class="auth-secondary" id="sendPhoneCode">获取验证码</button></div></div><div class="auth-field"><label>姓名（首次登录可选）</label><input id="phoneName" placeholder="例如：陈经理"></div><div class="auth-row"><button class="auth-primary" id="phoneLoginBtn" type="submit">登录 / 创建工作区</button></div><div class="auth-note">第一次用该手机号验证成功时，会自动创建一个独立个人工作区；不会加入任何已有团队。</div></form>`}
function registerHtml(){return `<div class="auth-head"><h2>注册 HUIDI</h2><p>先创建自己的工作区，之后再登记客户、开发客户和制作单据。</p></div><form id="registerForm"><div class="auth-field"><label>账号类型</label><select id="accountType"><option value="individual">个人使用</option><option value="team">公司 / 团队使用</option></select></div><div class="auth-field"><label>你的姓名</label><input id="regName" autocomplete="name" placeholder="例如：陈经理"></div><div class="auth-field auth-hidden" id="orgField"><label>公司 / 团队名称</label><input id="regOrg" placeholder="例如：汇迪五金有限公司"></div><div class="auth-field"><label>邮箱</label><input id="regEmail" type="email" autocomplete="email" placeholder="name@company.com"></div><div class="auth-field"><label>密码</label><input id="regPassword" type="password" minlength="8" autocomplete="new-password" placeholder="至少 8 位"></div><div class="auth-row"><button class="auth-primary" id="registerBtn" type="submit">创建工作区</button></div></form><div id="authMsg" class="auth-note auth-hidden"></div><div class="auth-foot"><span>已有账号？</span><a class="auth-link" href="/login">直接登录</a></div><div class="auth-security">每次公开注册都会创建新的独立工作区，不会自动加入 HUIDI 历史工作区或其他公司的数据库。</div>`}
function forgotHtml(){return `<div class="auth-head"><h2>重置密码</h2><p>填写注册邮箱。为避免泄露账号是否存在，系统始终返回统一提示。</p></div><form id="forgotForm"><div class="auth-field"><label>邮箱</label><input id="forgotEmail" type="email" autocomplete="email" placeholder="name@company.com"></div><div class="auth-row"><button class="auth-primary" id="forgotBtn" type="submit">发送重置说明</button></div></form><div id="authMsg" class="auth-note auth-hidden"></div><div class="auth-foot"><a class="auth-link" href="/login">← 返回登录</a></div>`}
function resetHtml(){return `<div class="auth-head"><h2>设置新密码</h2><p>重置成功后，之前已登录的会话会全部失效，需要重新登录。</p></div><form id="resetForm"><div class="auth-field"><label>新密码</label><input id="resetPassword" type="password" minlength="8" autocomplete="new-password" placeholder="至少 8 位"></div><div class="auth-field"><label>再次输入</label><input id="resetPassword2" type="password" minlength="8" autocomplete="new-password"></div><div class="auth-row"><button class="auth-primary" id="resetBtn" type="submit">确认重置</button></div></form><div id="authMsg" class="auth-note auth-hidden"></div><div class="auth-foot"><a class="auth-link" href="/login">← 返回登录</a></div>`}
function render(){const card=$('#authCard'),view=pathMode();card.innerHTML=view==='register'?registerHtml():view==='forgot'?forgotHtml():view==='reset'?resetHtml():loginHtml();bind();const err=new URL(location.href).searchParams.get('error');if(err)note(err,'error')}
function bind(){const view=pathMode();if(view==='login'){document.querySelectorAll('[data-login-tab]').forEach(b=>b.onclick=()=>{if(b.disabled)return;mode=b.dataset.loginTab;render()});$('#emailLoginForm')?.addEventListener('submit',loginEmail);$('#phoneLoginForm')?.addEventListener('submit',loginPhone);$('#sendPhoneCode')?.addEventListener('click',sendPhoneCode);document.querySelectorAll('[data-oauth]').forEach(b=>b.onclick=()=>oauth(b.dataset.oauth,b));return}if(view==='register'){$('#accountType').onchange=()=>$('#orgField').classList.toggle('auth-hidden',$('#accountType').value!=='team');$('#registerForm').addEventListener('submit',register);return}if(view==='forgot'){$('#forgotForm').addEventListener('submit',forgot);return}if(view==='reset'){$('#resetForm').addEventListener('submit',resetPassword)}}
async function loginEmail(e){e.preventDefault();const btn=$('#loginBtn');busy(btn,true,'登录中…');note('');try{await api('/api/auth/login',{method:'POST',body:JSON.stringify({email:$('#loginEmail').value,password:$('#loginPassword').value})});location.href='/'}catch(err){note(err.message,'error');busy(btn,false)}}
async function sendPhoneCode(){const btn=$('#sendPhoneCode');busy(btn,true,'发送中…');note('');try{await api('/api/auth/phone/code',{method:'POST',body:JSON.stringify({phone:$('#loginPhone').value})});note('验证码已发送，10 分钟内有效。','ok');let remain=60;const timer=setInterval(()=>{remain--;btn.textContent=remain>0?`${remain}s 后重发`:'重新获取';if(remain<=0){clearInterval(timer);btn.disabled=false}},1000)}catch(err){note(err.message,'error');busy(btn,false)}}
async function loginPhone(e){e.preventDefault();const btn=$('#phoneLoginBtn');busy(btn,true,'验证中…');note('');try{await api('/api/auth/phone/verify',{method:'POST',body:JSON.stringify({phone:$('#loginPhone').value,code:$('#phoneCode').value,display_name:$('#phoneName').value})});location.href='/'}catch(err){note(err.message,'error');busy(btn,false)}}
async function oauth(provider,btn){busy(btn,true,'正在打开…');note('');try{const out=await api(`/api/auth/oauth/${encodeURIComponent(provider)}/start?next=%2F`);location.href=out.authorize_url}catch(err){note(err.message,'error');busy(btn,false)}}
async function register(e){e.preventDefault();const btn=$('#registerBtn');busy(btn,true,'创建中…');note('');const payload={account_type:$('#accountType').value,display_name:$('#regName').value,organization_name:$('#regOrg')?.value||'',email:$('#regEmail').value,password:$('#regPassword').value};try{await api('/api/auth/register',{method:'POST',body:JSON.stringify(payload)});location.href='/'}catch(err){note(err.message,'error');busy(btn,false)}}
async function forgot(e){e.preventDefault();const btn=$('#forgotBtn');busy(btn,true,'提交中…');note('');try{const out=await api('/api/auth/password/forgot',{method:'POST',body:JSON.stringify({email:$('#forgotEmail').value})});note(out.email_service_ready?out.message:'账号重置接口已经启用，但当前服务器还没有配置认证邮件发送账号。','ok');busy(btn,false)}catch(err){note(err.message,'error');busy(btn,false)}}
async function resetPassword(e){e.preventDefault();const p1=$('#resetPassword').value,p2=$('#resetPassword2').value,btn=$('#resetBtn'),token=new URL(location.href).searchParams.get('token')||'';if(p1!==p2)return note('两次输入的密码不一致。','error');if(p1.length<8)return note('密码至少 8 位。','error');busy(btn,true,'重置中…');note('');try{const out=await api('/api/auth/password/reset',{method:'POST',body:JSON.stringify({token,password:p1})});note(out.message||'密码已重置。','ok');setTimeout(()=>location.href='/login',900)}catch(err){note(err.message,'error');busy(btn,false)}}
async function boot(){try{status=await api('/api/auth/status');if(!status.enabled){$('#authCard').innerHTML='<div class="auth-head"><h2>登录尚未启用</h2><p>当前部署还没有开启 HUIDI 账号门禁。</p></div><div class="auth-note">请先在服务器启用 HUIDI_TEAM_ACCESS。</div>';return}try{await api('/api/team/me');location.href='/';return}catch(_){}render()}catch(err){$('#authCard').innerHTML=`<div class="auth-head"><h2>暂时无法登录</h2><p>${esc(err.message)}</p></div>`}}
boot();
})();
