(()=>{'use strict';
if(window.HUIDIBeginnerFlow)return;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let lastData=null;
async function api(url){const r=await fetch(url);if(!r.ok)throw new Error(await r.text()||r.statusText);return r.json()}
function css(){if($('#bfCss'))return;const s=document.createElement('style');s.id='bfCss';s.textContent=`.bf{background:#fff;border:1px solid #e1e7ef;border-radius:14px;padding:13px 14px;margin:0 0 14px;box-shadow:0 9px 26px rgba(28,45,82,.055)}.bf-top{display:flex;align-items:center;justify-content:space-between;gap:12px}.bf-kicker{font-size:10px;font-weight:900;color:#1769ff}.bf h2{font-size:16px;margin:3px 0 0}.bf-now{margin-top:10px;border:1px solid #d8e7ff;background:#f6f9ff;border-radius:11px;padding:10px 11px;display:flex;justify-content:space-between;align-items:center;gap:12px}.bf-now b{display:block;font-size:12px;color:#274567}.bf-now span{display:block;font-size:10px;color:#6f7e91;line-height:1.5;margin-top:3px}.bf-btn{border:1px solid #d7e0ea;background:#fff;color:#36516f;border-radius:8px;padding:7px 9px;font-size:10px;font-weight:850;cursor:pointer;white-space:nowrap}.bf-btn.primary{background:#1769ff;border-color:#1769ff;color:#fff}.bf-flow{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px;margin-top:9px}.bf-step{border:1px solid #e2e8f0;background:#fff;border-radius:9px;padding:8px 9px;text-align:left;cursor:pointer;min-width:0}.bf-step:hover{border-color:#bdd3ef;background:#f9fbff}.bf-step b{display:block;font-size:10px;color:#334e6d;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.bf-step span{display:block;font-size:8.5px;color:#7c8999;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.bf-step.ready{background:#f5fbf8;border-color:#d8ebdf}.bf-step.attn{background:#fff8f2;border-color:#f1dfc9}.bf-quick{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px;padding-top:9px;border-top:1px solid #edf1f5}.bf-tip{font-size:9px;color:#7c8999;margin-left:auto;align-self:center}@media(max-width:900px){.bf-flow{grid-template-columns:1fr 1fr}.bf-now{align-items:flex-start;flex-direction:column}.bf-tip{width:100%;margin-left:0}}`;document.head.appendChild(s)}
function install(){if($('#beginnerFlow'))return;const sec=document.createElement('section');sec.id='beginnerFlow';sec.className='bf';sec.innerHTML=`<div class="bf-top"><div><div class="bf-kicker">工作引导</div><h2>不用找入口，按当前事情往下做</h2></div><button class="bf-btn" data-bf-action="refresh">刷新</button></div><div class="bf-now" id="bfNow"><div><b>正在整理现在最该做的事…</b><span>客户回复、到期跟进和询盘下一步会优先排在前面。</span></div></div><div class="bf-flow" id="bfFlow"></div><div class="bf-quick"><button class="bf-btn" data-bf-action="find">找客户</button><button class="bf-btn" data-bf-action="product">产品资料</button><button class="bf-btn" data-bf-action="mail">回复 / 发邮件</button><button class="bf-btn" data-bf-action="deals">客户 / 询盘</button><button class="bf-btn" data-bf-action="quotation">做报价</button><button class="bf-btn" data-bf-action="tariff">查关税</button><button class="bf-btn" data-bf-action="shipping">查船期</button><span class="bf-tip">客户回复或转询盘后，下一步会自动回到“今天”。</span></div>`;const dw=$('#dailyWorkbench'),search=$('.search');if(dw)dw.insertAdjacentElement('afterend',sec);else if(search)search.parentNode.insertBefore(sec,search);else $('.main')?.prepend(sec);sec.addEventListener('click',e=>{const action=e.target.closest('[data-bf-action]')?.dataset.bfAction;if(action)run(action)})}
function countOverdue(data){return [...(data.followups||[]),...(data.deal_tasks||[])].filter(x=>x.due_state==='overdue').length}
function recommendation(data){const m=data.mail||{},l=data.leads||{},overdue=countOverdue(data),tasks=(data.followups||[]).length+(data.deal_tasks||[]).length;if(Number(m.needs_reply||0)>0)return{title:`先回复 ${m.needs_reply} 位客户`,desc:'客户已经回信，优先回复比继续找新客户更重要。',action:'mail',label:'打开客户回复'};if(overdue>0)return{title:`先处理 ${overdue} 项逾期事情`,desc:'这些跟进或询盘下一步已经超过计划时间。',action:'followups',label:'查看逾期事项'};if(Number(m.connected_mailboxes||0)===0)return{title:'先连接一个常用邮箱',desc:'连接后才能在 HUIDI 里收回复、直接发信和自动停止后续冷开发。',action:'mail',label:'连接邮箱'};if(Number(m.pending||0)>0)return{title:`检查 ${m.pending} 封待发送邮件`,desc:'已确认的邮件正在等待发送，先确认发送状态再继续开发。',action:'queue',label:'查看待发送'};if(Number(l.total||0)===0)return{title:'先找到第一批潜在客户',desc:'填写产品和目标市场，系统只会保存真实搜索到的公司。',action:'find',label:'开始找客户'};if(Number(l.converted||0)>0||tasks>0)return{title:'继续推进已有客户和询盘',desc:'优先把已有机会往报价、确认和下一步推进，再补充新客户。',action:'deals',label:'打开客户 / 询盘'};return{title:'继续开发下一批客户',desc:'现有待办比较轻，可以继续补充潜在客户并完善联系人。',action:'find',label:'继续找客户'}}
function step(name,sub,action,kind=''){return `<button class="bf-step ${kind}" data-bf-action="${esc(action)}"><b>${esc(name)}</b><span>${esc(sub)}</span></button>`}
function render(data){lastData=data;const m=data.mail||{},l=data.leads||{},tasks=(data.followups||[]).length+(data.deal_tasks||[]).length,r=recommendation(data);$('#bfNow').innerHTML=`<div><b>${esc(r.title)}</b><span>${esc(r.desc)}</span></div><button class="bf-btn primary" data-bf-action="${esc(r.action)}">${esc(r.label)}</button>`;const total=Number(l.total||0),connected=Number(m.connected_mailboxes||0),replies=Number(m.needs_reply||0),converted=Number(l.converted||0),pending=Number(m.pending||0);$('#bfFlow').innerHTML=[step('① 找客户',total?`已有 ${total} 个潜在客户`:'从产品和市场开始','find',total?'ready':''),step('② 联系客户',connected?`已连接 ${connected} 个邮箱`:'先连接邮箱','mail',connected?'ready':'attn'),step('③ 跟进回复',replies?`${replies} 个客户待回复`:tasks?`${tasks} 项待推进`:'当前无紧急回复',replies?'mail':'followups',replies?'attn':tasks?'ready':''),step('④ 询盘 / 报价',converted?`已有 ${converted} 笔正式机会`:'客户有意向后转询盘','deals',converted?'ready':''),step('⑤ 单据 / 出运',pending?`另有 ${pending} 封待发送`:'沿同一笔业务继续','quotation')].join('')}
function click(selector){const el=$(selector);if(el){el.click();return true}return false}
function run(action){if(action==='refresh')return refresh();if(action==='find'){const search=$('.search');search?.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>$('#keyword')?.focus(),180);return}if(action==='product')return window.HUIDIProductBrain?.open?.();if(action==='mail')return window.HUIDIDailyServices?.open?.('mail');if(action==='queue')return window.HUIDIDailyServices?.open?.('queue');if(action==='deals')return window.HUIDIBusinessCenter?.open?.('deals');if(action==='quotation'){if(click('[data-huidi-business="quotation"]'))return;return window.HUIDIBusinessCenter?.open?.('deals')}if(action==='tariff')return window.HUIDIDailyServices?.open?.('tariff');if(action==='shipping')return window.HUIDIDailyServices?.open?.('shipping');if(action==='followups'){const el=$('#dwFollowups')||$('#dailyWorkbench');el?.scrollIntoView({behavior:'smooth',block:'center'})}}
async function refresh(){install();try{render(await api('/api/workbench/today'))}catch(e){const msg=window.HUIDIPlainLanguage?.message?.(e?.message||e)||'暂时无法整理工作，请稍后重试。';$('#bfNow').innerHTML=`<div><b>暂时无法整理下一步</b><span>${esc(msg)}</span></div><button class="bf-btn" data-bf-action="refresh">重新读取</button>`}}
function boot(){css();install();refresh();document.addEventListener('click',e=>{if(e.target.closest('#approveDraft,#mgSend,#saveFollow,#syncLocal,#searchBtn,[data-hs-sync],[data-run-queue],[data-save-deal]'))setTimeout(refresh,900)},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.HUIDIBeginnerFlow=Object.freeze({refresh,run,get data(){return lastData}});
})();