(()=>{'use strict';
if(window.HUIDIIntelligenceHistory)return;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let leadId='';
const friendly=e=>window.HUIDIPlainLanguage?.message?.(e?.message||e)||String(e?.message||e||'暂时无法读取联网资料');
async function api(url){const r=await fetch(url);if(!r.ok)throw new Error(await r.text()||r.statusText);return r.json()}
const kindName=k=>({company:'企业核验',trade:'贸易记录',tariff:'关税资料',fx:'汇率记录',shipping:'船期 / 物流',market_news:'市场动态'})[k]||'联网资料';
function css(){if($('#ihCss'))return;const s=document.createElement('style');s.id='ihCss';s.textContent=`.ih-box{border:1px solid #dfe7ef;background:#fbfcfe;border-radius:11px;padding:10px}.ih-head{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.ih-head h3{margin:0;font-size:12px}.ih-head small{display:block;margin-top:3px;color:#7b8898;font-size:8.5px}.ih-actions{display:flex;gap:5px;flex-wrap:wrap}.ih-btn{border:1px solid #d8e1eb;background:#fff;border-radius:8px;padding:6px 8px;font-size:8.5px;font-weight:850;color:#35516f;cursor:pointer}.ih-list{display:grid;gap:5px;margin-top:8px}.ih-item{border:1px solid #e6ebf1;background:#fff;border-radius:8px;padding:7px 8px}.ih-item b{display:block;font-size:9px;color:#344c69}.ih-item span{display:block;margin-top:2px;color:#728096;font-size:8px;line-height:1.5}.ih-item small{display:block;margin-top:3px;color:#9aa4b1;font-size:7.5px}.ih-empty{padding:8px 0;color:#8793a2;font-size:8.5px}`;document.head.appendChild(s)}
function install(){if($('#ihBox'))return;const assessment=$('#assessmentBox')?.closest('.section');if(!assessment)return;const sec=document.createElement('div');sec.className='section';sec.innerHTML='<div id="ihBox" class="ih-box"><div class="ih-empty">打开客户后显示已经查询过的企业、贸易、关税、汇率和物流资料。</div></div>';assessment.after(sec)}
function first(obj,keys){for(const k of keys){const v=obj?.[k];if(v!==undefined&&v!==null&&v!==''&&(!Array.isArray(v)||v.length))return v}return''}
function text(v){if(Array.isArray(v))return v.slice(0,3).map(x=>typeof x==='object'?first(x,['name','company','product','title','value']):x).filter(Boolean).join('、');if(typeof v==='object'&&v)return first(v,['name','company','title','value'])||'';return String(v??'')}
function compactNormalized(item){const n=item?.normalized||{},kind=item?.kind;if(!n||typeof n!=='object')return'已保存，可在需要时继续使用。';if(kind==='company'){const parts=[first(n,['legal_name','company_name','name']),first(n,['status','company_status']),first(n,['country']),first(n,['industry']),first(n,['risk_level','risk_score'])];return parts.map(text).filter(Boolean).slice(0,4).join(' · ')||'企业资料已保存，可继续用于客户核对。'}if(kind==='trade'){const count=first(n,['total_records','trade_count','records_count']),date=first(n,['latest_trade_date','last_trade_date']),products=first(n,['products','product']),hs=first(n,['hs_codes','hs_code']);return [count!==''?`贸易记录 ${text(count)} 条`:'',date?`最近 ${text(date)}`:'',products?`产品 ${text(products)}`:'',hs?`HS ${text(hs)}`:''].filter(Boolean).join(' · ')||'贸易资料已保存，可继续用于判断采购情况。'}if(kind==='tariff'){const hs=first(n,['hs_code']),duty=first(n,['duty_rate','tariff_rate']),vat=first(n,['vat_rate']),dest=first(n,['destination','country']);return [hs?`HS ${text(hs)}`:'',duty!==''?`关税 ${text(duty)}`:'',vat!==''?`进口税 ${text(vat)}`:'',dest?text(dest):''].filter(Boolean).join(' · ')||'关税资料已保存，可继续用于报价核对。'}if(kind==='fx'){const base=first(n,['base_currency','base']),quote=first(n,['quote_currency','quote']),rate=first(n,['rate']),date=first(n,['date']);return [base&&quote?`${text(base)} → ${text(quote)}`:'',rate!==''?`参考汇率 ${text(rate)}`:'',date?text(date):''].filter(Boolean).join(' · ')||'汇率记录已保存。'}if(kind==='shipping'){const origin=first(n,['origin_port','origin']),dest=first(n,['destination_port','destination']),etd=first(n,['etd']),eta=first(n,['eta']),carrier=first(n,['carrier']);return [origin&&dest?`${text(origin)} → ${text(dest)}`:'',carrier?text(carrier):'',etd?`开船 ${text(etd)}`:'',eta?`到港 ${text(eta)}`:''].filter(Boolean).join(' · ')||'船期 / 物流资料已保存，可继续用于出运安排。'}if(kind==='market_news'){const titles=first(n,['titles','title','summary']);return text(titles)||'市场动态已保存，可继续用于客户判断。'}return'联网资料已保存，可在需要时继续使用。'}
async function refresh(){install();const box=$('#ihBox');if(!box||!leadId)return;try{const out=await api(`/api/intelligence/summary/${leadId}`),rows=out.items||[];box.innerHTML=`<div class="ih-head"><div><h3>联网资料</h3><small>查过的数据会留在当前客户下面，后续跟进和业务推进可以继续用。</small></div><div class="ih-actions"><button class="ih-btn" data-ih-company>企业核验</button><button class="ih-btn" data-ih-trade>贸易记录</button></div></div><div class="ih-list">${rows.length?rows.map(x=>`<div class="ih-item"><b>${esc(kindName(x.kind))}${x.title?` · ${esc(x.title)}`:''}</b><span>${esc(compactNormalized(x))}</span><small>${esc((x.checked_at||'').replace('T',' ').slice(0,16))}</small></div>`).join(''):'<div class="ih-empty">这个客户还没有联网资料。需要时再查，不强制每个潜在客户都做完整背调。</div>'}</div>`;$('[data-ih-company]')?.addEventListener('click',()=>window.HUIDIDailyServices?.open?.('company'));$('[data-ih-trade]')?.addEventListener('click',()=>window.HUIDIDailyServices?.open?.('trade'))}catch(e){box.innerHTML=`<div class="ih-empty">${esc(friendly(e))}</div>`}}
function bind(){document.addEventListener('click',e=>{const o=e.target.closest('[data-open]');if(o){leadId=String(o.dataset.open||'');setTimeout(refresh,160);return}if(leadId&&e.target.closest('[data-company-check],[data-trade],[data-tariff],[data-fx],[data-shipping],[data-intel]'))setTimeout(refresh,1200)},true)}
function boot(){css();install();bind()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.HUIDIIntelligenceHistory=Object.freeze({refresh});
})();