(()=>{'use strict';
if(window.HUIDIIntelligenceHistory)return;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let leadId='';
async function api(url){const r=await fetch(url);if(!r.ok)throw new Error(await r.text()||r.statusText);return r.json()}
const kindName=k=>({company:'企业核验',trade:'贸易记录',tariff:'关税资料',fx:'汇率记录',shipping:'船期 / 物流',market_news:'市场情报'})[k]||k;
function css(){if($('#ihCss'))return;const s=document.createElement('style');s.id='ihCss';s.textContent=`.ih-box{border:1px solid #dfe7ef;background:#fbfcfe;border-radius:11px;padding:10px}.ih-head{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.ih-head h3{margin:0;font-size:12px}.ih-head small{display:block;margin-top:3px;color:#7b8898;font-size:8.5px}.ih-actions{display:flex;gap:5px;flex-wrap:wrap}.ih-btn{border:1px solid #d8e1eb;background:#fff;border-radius:8px;padding:6px 8px;font-size:8.5px;font-weight:850;color:#35516f;cursor:pointer}.ih-list{display:grid;gap:5px;margin-top:8px}.ih-item{border:1px solid #e6ebf1;background:#fff;border-radius:8px;padding:7px 8px}.ih-item b{display:block;font-size:9px;color:#344c69}.ih-item span{display:block;margin-top:2px;color:#728096;font-size:8px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ih-item small{display:block;margin-top:3px;color:#9aa4b1;font-size:7.5px}.ih-empty{padding:8px 0;color:#8793a2;font-size:8.5px}`;document.head.appendChild(s)}
function install(){if($('#ihBox'))return;const assessment=$('#assessmentBox')?.closest('.section');if(!assessment)return;const sec=document.createElement('div');sec.className='section';sec.innerHTML='<div id="ihBox" class="ih-box"><div class="ih-empty">打开客户后显示已经查询过的企业、贸易、关税、汇率和物流资料。</div></div>';assessment.after(sec)}
function compactResult(item){const r=item?.result;if(!r)return '';if(typeof r==='string')return r.slice(0,160);try{const text=JSON.stringify(r);return text.length>180?text.slice(0,180)+'…':text}catch(_){return ''}}
async function refresh(){install();const box=$('#ihBox');if(!box||!leadId)return;try{const out=await api(`/api/intelligence/summary/${leadId}`),rows=out.items||[];box.innerHTML=`<div class="ih-head"><div><h3>联网资料</h3><small>查过的数据会留在当前客户下面，后续跟进和业务推进可以继续用。</small></div><div class="ih-actions"><button class="ih-btn" data-ih-company>企业核验</button><button class="ih-btn" data-ih-trade>贸易记录</button></div></div><div class="ih-list">${rows.length?rows.map(x=>`<div class="ih-item"><b>${esc(kindName(x.kind))} · ${esc(x.title||'')}</b><span>${esc(compactResult(x))}</span><small>${esc((x.checked_at||'').replace('T',' ').slice(0,16))}</small></div>`).join(''):'<div class="ih-empty">这个客户还没有联网资料。需要时再查，不强制每条线索都做完整背调。</div>'}</div>`;$('[data-ih-company]')?.addEventListener('click',()=>window.HUIDIDailyServices?.open?.('company'));$('[data-ih-trade]')?.addEventListener('click',()=>window.HUIDIDailyServices?.open?.('trade'))}catch(e){box.innerHTML=`<div class="ih-empty">联网资料暂时无法读取：${esc(e.message||e)}</div>`}}
function bind(){document.addEventListener('click',e=>{const o=e.target.closest('[data-open]');if(o){leadId=String(o.dataset.open||'');setTimeout(refresh,160);return}if(leadId&&e.target.closest('[data-company-check],[data-trade],[data-tariff],[data-fx],[data-shipping],[data-intel]'))setTimeout(refresh,1200)},true)}
function boot(){css();install();bind()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.HUIDIIntelligenceHistory=Object.freeze({refresh});
})();