(()=>{'use strict';
if(window.HUIDIMapView)return;
const $=s=>document.querySelector(s),clean=v=>String(v??'').trim(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let rows=[];
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});if(!r.ok){let msg=await r.text();try{msg=JSON.parse(msg).detail||msg}catch(_){}throw new Error(msg||r.statusText)}return r.json()}
function mapUrl(x){if(x.lat!==null&&x.lat!==undefined&&x.lng!==null&&x.lng!==undefined)return `https://www.google.com/maps?q=${encodeURIComponent(`${x.lat},${x.lng}`)}&z=14&output=embed`;const q=[x.name,x.address].filter(Boolean).join(' ');return `https://www.google.com/maps?q=${encodeURIComponent(q)}&output=embed`}
function renderMap(i=0){const pane=$('#huidiRealMap');const x=rows[i];if(!pane)return;if(!x){pane.innerHTML='<div class="hs-empty">选择左侧公司后查看地图。</div>';return}pane.innerHTML=`<iframe title="${esc(x.name||'地图位置')}" src="${esc(mapUrl(x))}" style="width:100%;height:100%;min-height:430px;border:0;border-radius:12px" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>`;document.querySelectorAll('[data-real-map-row]').forEach(n=>n.style.borderColor=Number(n.dataset.realMapRow)===i?'#8fb7ef':'')}
function renderResults(){const box=$('#hsMapResults');if(!box)return;box.innerHTML=`<div style="display:grid;grid-template-columns:minmax(280px,40%) minmax(360px,1fr);gap:10px;align-items:stretch"><div class="hs-list" id="huidiMapCompanies" style="max-height:520px;overflow:auto">${rows.length?rows.map((x,i)=>`<div class="hs-item" data-real-map-row="${i}" style="cursor:pointer"><b>${esc(x.name||'未命名公司')}</b><span>${esc([x.category,x.address,x.phone].filter(Boolean).join(' · '))}</span><small>${x.website?`<a href="${esc(x.website)}" target="_blank" rel="noreferrer">${esc(x.website)}</a>`:'暂未找到官网'}</small><div class="hs-row" style="margin-top:6px"><button class="hs-btn" data-real-map-show="${i}">看地图</button><button class="hs-btn primary" data-real-map-add="${i}">加入线索池</button></div></div>`).join(''):'<div class="hs-empty">没有找到合适结果，可以换一个行业词或地区。</div>'}</div><div id="huidiRealMap" style="min-height:430px;border:1px solid #e0e7f0;border-radius:12px;background:#f7f9fc;overflow:hidden"></div></div>`;box.querySelectorAll('[data-real-map-row]').forEach(n=>n.onclick=e=>{if(e.target.closest('a,button'))return;renderMap(Number(n.dataset.realMapRow))});box.querySelectorAll('[data-real-map-show]').forEach(n=>n.onclick=()=>renderMap(Number(n.dataset.realMapShow)));box.querySelectorAll('[data-real-map-add]').forEach(n=>n.onclick=()=>addLead(Number(n.dataset.realMapAdd)));if(rows.length)renderMap(0)}
async function search(){const box=$('#hsMapResults');if(!box)return;const keyword=clean($('#hsMapKeyword')?.value),location=clean($('#hsMapLocation')?.value),buyer=clean($('#hsMapBuyer')?.value);if(!keyword)return alert('先填写产品或行业');box.innerHTML='<div class="hs-empty">正在地图上查找附近公司…</div>';try{const out=await api('/api/tools/map-leads',{method:'POST',body:JSON.stringify({keyword,location,buyer_type:buyer,limit:30})});rows=out.items||[];renderResults()}catch(e){box.innerHTML=`<div class="hs-card"><div class="hs-note">${esc(e.message||e)}</div></div>`}}
async function addLead(i){const x=rows[i];if(!x)return;try{const out=await api('/api/tools/map-leads/import',{method:'POST',body:JSON.stringify({name:x.name,website:x.website||'',address:x.address||'',country:clean($('#hsMapLocation')?.value),phone:x.phone||'',category:x.category||'',product_keyword:clean($('#hsMapKeyword')?.value),buyer_type:clean($('#hsMapBuyer')?.value),source_url:x.source_url||''})});alert(out.created?'已加入线索池，可以继续背调和联系。':'这家公司已经在线索池里。');window.HUIDIDailyWorkbench?.refresh?.()}catch(e){alert(e.message||e)}}
function clickGuard(e){const b=e.target.closest?.('[data-map-search]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();search()}
function boot(){document.addEventListener('click',clickGuard,true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.HUIDIMapView=Object.freeze({search});
})();