(()=>{'use strict';
if(window.HUIDIWorkspacePages)return;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let bypass=false,docked=null,currentRoute='home',routeEpoch=0,surfaceCleanup=null;
const routeTitles={notifications:'提醒',contacts:'联系人',mail:'收件箱',sent:'已发送',mailbox:'邮箱设置',queue:'待发送',map:'地图找客户',company:'客户背调',trade:'贸易记录',tariff:'HS 编码 / 关税',fx:'汇率换算',shipping:'船期 / 物流',business:'客户 / 询盘',quotation:'报价单',proforma_invoice:'形式发票 PI',sales_contract:'销售合同',commercial_invoice:'商业发票 CI',packing_list:'装箱单',product:'产品资料',catalog:'产品目录',intelligence:'市场动态',sequences:'自动跟进',audit:'操作记录',services:'可用功能'};
const popupRoots=['#huidiNavBack','#huidiBusinessBack','#huidiServiceBack','#pbBackdrop','#huidiIntelBack','#sqBack','#auBack','#huidiStandaloneBusinessBack'];
function css(){if($('#huidiPageRouterCss'))return;const s=document.createElement('style');s.id='huidiPageRouterCss';s.textContent=`
.main.hpr-active{min-width:0}.main.hpr-active>:not(#huidiPageHost){display:none!important}.hpr-host{display:none;min-height:100vh;background:#f6f8fb}.hpr-host.open{display:grid;grid-template-rows:auto minmax(0,1fr)}.hpr-head{display:flex;align-items:center;gap:11px;padding:13px 18px 11px;border-bottom:1px solid #e4eaf1;background:#fff;position:sticky;top:0;z-index:6}.hpr-head button{border:1px solid #d8e1ec;background:#fff;border-radius:8px;padding:6px 9px;cursor:pointer;font-weight:800;color:#36516f}.hpr-head h1{margin:0;font-size:18px;color:#22354d}.hpr-head p{margin:2px 0 0;color:#768499;font-size:9px}.hpr-mount{min-width:0;min-height:0;padding:12px 14px 18px;overflow:auto}.hpr-docked{position:static!important;inset:auto!important;width:100%!important;height:auto!important;min-height:0!important;background:transparent!important;padding:0!important;display:block!important;z-index:auto!important}.hpr-docked.open{display:block!important}.hpr-docked>.hn-modal,.hpr-docked>.hb-modal,.hpr-docked>.hs-modal,.hpr-docked>.ci-modal,.hpr-docked>.sq-modal,.hpr-docked>.pb-modal,.hpr-docked>.au-panel,.hpr-docked>.has-modal,.hpr-docked>.ss-modal,.hpr-docked>.mg-modal{width:100%!important;max-width:none!important;height:auto!important;max-height:none!important;min-height:calc(100vh - 92px)!important;border-radius:10px!important;box-shadow:none!important;border:1px solid #dfe6ef!important}.hpr-docked>.au-panel{margin:0!important}.hpr-docked .hn-close,.hpr-docked .hb-close,.hpr-docked .hs-close,.hpr-docked .ci-close,.hpr-docked .sq-close,.hpr-docked .pb-close,.hpr-docked .au-close{display:none!important}.hpr-document{min-height:calc(100vh - 92px);background:#fff;border:1px solid #dfe6ef;border-radius:10px;overflow:hidden}.hpr-document iframe{display:block;width:100%;height:calc(100vh - 94px);border:0;background:#fff}.hpr-empty{padding:28px 12px;text-align:center;color:#8190a2;font-size:10px}@media(max-width:900px){.hpr-mount{padding:9px}}
`;document.head.appendChild(s)}
function host(){css();let h=$('#huidiPageHost');if(h)return h;const main=$('.main');if(!main)return null;h=document.createElement('section');h.id='huidiPageHost';h.className='hpr-host';h.innerHTML='<div class="hpr-head"><button data-hpr-home>← 工作台</button><div><h1 id="hprTitle">工作页面</h1><p id="hprDesc">左侧导航只切换一个主页面。</p></div></div><div class="hpr-mount" id="huidiPageMount"></div>';main.appendChild(h);h.querySelector('[data-hpr-home]').onclick=()=>showHome(true);h.addEventListener('click',e=>{if(e.target.closest('.hn-close,.hb-close,.hs-close,.ci-close,.sq-close,.pb-close,.au-close')){e.preventDefault();e.stopImmediatePropagation();showHome(true)}},true);return h}
function updateUrl(route,replace=false){try{const u=new URL(location.href);if(route&&route!=='home')u.searchParams.set('page',route);else u.searchParams.delete('page');history[replace?'replaceState':'pushState']({huidiPage:route},'',u.pathname+(u.searchParams.toString()?`?${u.searchParams}`:'')+u.hash)}catch(_){}}
function navActive(target){document.querySelectorAll('.side .nav a').forEach(x=>x.classList.toggle('active',x===target))}
function cleanupSurface(){const cleanup=surfaceCleanup;surfaceCleanup=null;if(cleanup)try{cleanup()}catch(_){}}
function closeStrays(keep=null){for(const selector of popupRoots){const node=$(selector);if(!node||node===keep||node===docked?.node)continue;node.classList.remove('open','hpr-docked')}document.body.style.overflow=''}
function restoreDock(){if(!docked)return;try{docked.node.classList.remove('hpr-docked','open');(docked.parent||document.body).appendChild(docked.node)}catch(_){}docked=null;document.body.style.overflow=''}
function mountPage(route,title,desc=''){const h=host();if(!h)return null;routeEpoch+=1;cleanupSurface();restoreDock();closeStrays();currentRoute=route;$('.main')?.classList.add('hpr-active');h.classList.add('open');$('#hprTitle').textContent=title||routeTitles[route]||'工作页面';$('#hprDesc').textContent=desc||'左侧导航只切换一个主页面，不再叠加窗口。';const m=$('#huidiPageMount');m.innerHTML='';m.dataset.routeEpoch=String(routeEpoch);updateUrl(route);window.scrollTo({top:0,behavior:'auto'});return m}
function showHome(push=false,anchor=''){routeEpoch+=1;cleanupSurface();restoreDock();closeStrays();currentRoute='home';$('.main')?.classList.remove('hpr-active');$('#huidiPageHost')?.classList.remove('open');if(push)updateUrl('home');if(anchor)setTimeout(()=>$(anchor)?.scrollIntoView({behavior:'smooth',block:'start'}),20)}
async function waitFor(selector,token){for(let i=0;i<40;i++){if(token!==routeEpoch)return null;const n=$(selector);if(n&&n.classList.contains('open'))return n;await new Promise(r=>setTimeout(r,20))}return token===routeEpoch?$(selector):null}
async function dock(route,title,selector,invoke,desc=''){const m=mountPage(route,title,desc);if(!m)return;const token=routeEpoch;try{await invoke();if(token!==routeEpoch){$(selector)?.classList.remove('open','hpr-docked');return}const node=await waitFor(selector,token);if(token!==routeEpoch){node?.classList.remove('open','hpr-docked');return}if(!node)throw new Error('页面组件没有正常打开');const parent=node.parentElement;closeStrays(node);node.classList.add('hpr-docked','open');m.appendChild(node);docked={node,parent,route};document.body.style.overflow=''}catch(e){if(token!==routeEpoch)return;m.innerHTML=`<div class="hpr-empty">${esc(e?.message||e||'页面暂时无法打开')}</div>`}}
async function openNavigationPage(view){const route=view==='notifications'?'notifications':'contacts',title=routeTitles[route],desc=route==='notifications'?'客户回复、到期跟进、业务下一步和邮件异常集中处理。':'已确认联系人集中管理，点联系人可回到对应客户继续。';if(!window.HUIDIDailyNavigation?.mount)return dock(route,title,'#huidiNavBack',()=>route==='notifications'?window.HUIDIDailyNavigation?.notifications?.():window.HUIDIDailyNavigation?.contacts?.(),desc);const m=mountPage(route,title,desc);if(!m)return;const token=routeEpoch;surfaceCleanup=()=>window.HUIDIDailyNavigation?.unmount?.();try{await window.HUIDIDailyNavigation.mount(m,route);if(token!==routeEpoch)return;closeStrays($('#huidiNavBack'));document.body.style.overflow=''}catch(e){if(token!==routeEpoch)return;cleanupSurface();m.innerHTML=`<div class="hpr-empty">${esc(e?.message||e||`${title}页面暂时无法打开`)}</div>`}}
async function openBusinessPage(target){const v=target?.dataset?.huidiBusiness||'deals',route=v==='deals'?'business':v,doc=v==='deals'?'':v;if(!window.HUIDIBusinessCenter?.mount)return dock(route,routeTitles[route]||'客户 / 询盘','#huidiBusinessBack',()=>window.HUIDIBusinessCenter?.open?.('deals',1,doc),'客户、询盘和单据沿同一笔业务继续。');const m=mountPage(route,routeTitles[route]||'客户 / 询盘','客户、询盘和单据沿同一笔业务继续；主操作固定在页面内，不再套一层弹窗。');if(!m)return;const token=routeEpoch;surfaceCleanup=()=>window.HUIDIBusinessCenter?.unmount?.();try{await window.HUIDIBusinessCenter.mount(m,'deals',1,doc);if(token!==routeEpoch)return;closeStrays($('#huidiBusinessBack'));document.body.style.overflow=''}catch(e){if(token!==routeEpoch)return;cleanupSurface();m.innerHTML=`<div class="hpr-empty">${esc(e?.message||e||'客户 / 询盘页面暂时无法打开')}</div>`}}
async function openSequencePage(){if(!window.HUIDISequenceUI?.mount)return dock('sequences','自动跟进','#sqBack',()=>window.HUIDISequenceUI?.open?.(),'已确认的跟进内容和运行中的客户集中在这里。');const m=mountPage('sequences','自动跟进','统一查看已确认的跟进内容和运行中的客户；从客户详情启用时仍保留短流程入口。');if(!m)return;const token=routeEpoch;surfaceCleanup=()=>window.HUIDISequenceUI?.unmount?.();try{await window.HUIDISequenceUI.mount(m);if(token!==routeEpoch)return;closeStrays($('#sqBack'));document.body.style.overflow=''}catch(e){if(token!==routeEpoch)return;cleanupSurface();m.innerHTML=`<div class="hpr-empty">${esc(e?.message||e||'自动跟进页面暂时无法打开')}</div>`}}
async function openProductPage(target){if(target)navActive(target);if(!window.HUIDIProductBrain?.mount)return dock('product','产品资料','#pbBackdrop',()=>window.HUIDIProductBrain?.open?.(),'维护产品名称、规格、MOQ、交期、包装和对外可用事实。');const m=mountPage('product','产品资料','维护长期可复用的产品事实；客户临时要求仍留在客户或询盘中。');if(!m)return;const token=routeEpoch;surfaceCleanup=()=>window.HUIDIProductBrain?.unmount?.();try{await window.HUIDIProductBrain.mount(m);if(token!==routeEpoch)return;closeStrays($('#pbBackdrop'));document.body.style.overflow=''}catch(e){if(token!==routeEpoch)return;cleanupSurface();m.innerHTML=`<div class="hpr-empty">${esc(e?.message||e||'产品资料页面暂时无法打开')}</div>`}}
function openNativeDocument(url,type='quotation'){try{const u=new URL(url,location.origin);if(u.origin!==location.origin)throw new Error('单据地址不是当前 Online 工作台');const route=routeTitles[type]?type:'business',m=mountPage(route,routeTitles[route]||'单据','Online 原生单据在当前工作区继续处理，不再打开第二个窗口。');if(!m)return null;m.innerHTML=`<div class="hpr-document"><iframe id="hwpDocumentFrame" title="${esc(routeTitles[route]||'单据')}" src="${esc(u.pathname+u.search+u.hash)}"></iframe></div>`;return $('#hwpDocumentFrame')}catch(e){const m=mountPage('business','单据');if(m)m.innerHTML=`<div class="hpr-empty">${esc(e?.message||e)}</div>`;return null}}
function routeTarget(target){if(target.hasAttribute('data-huidi-notifications'))return openNavigationPage('notifications');if(target.hasAttribute('data-huidi-contacts'))return openNavigationPage('contacts');if(target.hasAttribute('data-huidi-product'))return openProductPage(target);if(target.hasAttribute('data-huidi-catalog'))return window.HUIDIOnlineCatalog?.open?.();if(target.hasAttribute('data-huidi-intelligence'))return dock('intelligence','市场动态','#huidiIntelBack',()=>window.HUIDICustomerIntelligence?.open?.(),'全球市场、政策、物流与客户相关动态在独立页面查看。');if(target.hasAttribute('data-huidi-business'))return openBusinessPage(target);if(target.hasAttribute('data-huidi-service')){const v=target.dataset.huidiService||'services',detail=v==='mail'?(target.dataset.huidiMailFolder||'inbox'):'';const route=v==='mail'?(detail==='sent'?'sent':'mail'):v;return dock(route,routeTitles[route]||target.textContent,'#huidiServiceBack',()=>window.HUIDIDailyServices?.open?.(v,detail),'该功能在主工作区内独立显示。')}if(target.hasAttribute('data-huidi-sequences'))return openSequencePage();if(target.hasAttribute('data-huidi-audit'))return dock('audit','操作记录','#auBack',()=>window.HUIDIAuditUI?.open?.(),'查看客户、邮件、询盘、产品和团队操作记录。');if(target.hasAttribute('data-huidi-service-settings')||target.hasAttribute('data-huidi-admin-safety')){bypass=true;try{target.click()}finally{bypass=false}return}const action=target.dataset.huidiNav;if(action){showHome(true,action==='find'?'.search':action==='leads'?'.table-wrap':action==='followups'?'#dwFollowups':action==='today'?'#dailyWorkbench':'')}}
function click(e){if(bypass)return;const target=e.target.closest('.side [data-huidi-nav],.side [data-huidi-notifications],.side [data-huidi-contacts],.side [data-huidi-product],.side [data-huidi-catalog],.side [data-huidi-intelligence],.side [data-huidi-business],.side [data-huidi-service],.side [data-huidi-sequences],.side [data-huidi-audit],.side [data-huidi-service-settings],.side [data-huidi-admin-safety]');if(!target)return;e.preventDefault();e.stopImmediatePropagation();navActive(target);routeTarget(target)}
function selectorFor(page){return{contacts:'[data-huidi-contacts]',notifications:'[data-huidi-notifications]',product:'[data-huidi-product]',catalog:'[data-huidi-catalog]',intelligence:'[data-huidi-intelligence]',sequences:'[data-huidi-sequences]',audit:'[data-huidi-audit]',business:'[data-huidi-business="deals"]',quotation:'[data-huidi-business="quotation"]',proforma_invoice:'[data-huidi-business="proforma_invoice"]',sales_contract:'[data-huidi-business="sales_contract"]',commercial_invoice:'[data-huidi-business="commercial_invoice"]',packing_list:'[data-huidi-business="packing_list"]',mail:'[data-huidi-service="mail"]',sent:'[data-huidi-service="mail"][data-huidi-mail-folder="sent"]',queue:'[data-huidi-service="queue"]',map:'[data-huidi-service="map"]',company:'[data-huidi-service="company"]',trade:'[data-huidi-service="trade"]',tariff:'[data-huidi-service="tariff"]',fx:'[data-huidi-service="fx"]',shipping:'[data-huidi-service="shipping"]'}[page]}
function restoreFromUrl(){const page=new URL(location.href).searchParams.get('page');if(!page||page==='home')return;setTimeout(()=>{const find=selectorFor(page),el=find?$(find):null;if(el){navActive(el);routeTarget(el)}},80)}
document.addEventListener('click',click,true);window.addEventListener('popstate',()=>{const page=new URL(location.href).searchParams.get('page');if(!page)showHome(false);else restoreFromUrl()});
function boot(){host();restoreFromUrl()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.HUIDIWorkspacePages=Object.freeze({open:route=>{if(route==='catalog')return window.HUIDIOnlineCatalog?.open?.();const find=selectorFor(route),el=find?$(find):null;if(el)return routeTarget(el)},openDocument:openNativeDocument,mount:mountPage,epoch:()=>routeEpoch,home:()=>showHome(true),current:()=>currentRoute});
})();