(()=>{'use strict';
const core=window.HUIDIProductBrainCore;if(!core)return;
const KEY='huidi_online_product_brains_v1',ACTIVE='huidi_online_product_brain_active_v1',MAX_ROWS=500,LIST_PAGE_SIZE=50;
const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const clean=v=>String(v??'').trim();
const lines=v=>Array.isArray(v)?v.map(clean).filter(Boolean):String(v??'').split(/\r?\n|[；;]/).map(clean).filter(Boolean);
const read=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch(_){return[]}};
const write=rows=>localStorage.setItem(KEY,JSON.stringify(rows.slice(0,MAX_ROWS)));
const activeId=()=>localStorage.getItem(ACTIVE)||'';
const active=()=>read().find(x=>String(x.id)===String(activeId()))||read()[0]||null;
const imageOf=x=>clean(x?.image_url||x?.main_image||x?.image||x?.cover_image||x?.thumbnail||'');
let surface='modal',pageHost=null,editId='',listPage=1,listQuery='',dirty=false,saveNote='';
function setActive(id){localStorage.setItem(ACTIVE,String(id||''));renderBar();renderList();renderDraftSummary()}
function css(){if($('#pbCss'))return;const s=document.createElement('style');s.id='pbCss';s.textContent=`
.pb-bar{margin:0 0 12px;border:1px solid #dfe6ef;background:#fff;border-radius:12px;padding:11px 12px;display:flex;align-items:center;gap:12px;justify-content:space-between}.pb-main{display:flex;align-items:center;gap:10px;min-width:0}.pb-mark{width:38px;height:38px;border-radius:9px;background:#f1f5f9;color:#33506f;display:grid;place-items:center;font-size:10px;font-weight:900;overflow:hidden;flex:0 0 auto}.pb-mark img{width:100%;height:100%;object-fit:cover}.pb-copy{min-width:0}.pb-copy b{display:block;font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:#263b52}.pb-copy small{display:block;color:#728196;font-size:9px;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pb-actions{display:flex;align-items:center;gap:6px;flex-wrap:wrap}.pb-mini{border:1px solid #d8e1ec;background:#fff;border-radius:8px;padding:7px 9px;font-size:9px;font-weight:800;color:#35506d;cursor:pointer;line-height:1.2}.pb-mini:hover{background:#f6f9fc}.pb-mini.primary{background:#1769ff;border-color:#1769ff;color:#fff}.pb-mini.primary:hover{background:#0f5eea}.pb-mini:disabled{cursor:default;opacity:.52}.pb-progress{font-size:8.5px;color:#58708b;background:#f0f4f8;border-radius:999px;padding:4px 7px;font-weight:800}.pb-campaign{margin-top:7px}.pb-chips{display:flex;gap:4px;flex-wrap:wrap;margin-top:4px}.pb-chip{border-radius:999px;padding:3px 6px;background:#f2f5f8;color:#617289;font-size:8px}.pb-inline-use{margin-top:6px;border:1px solid #c9dbf7;background:#f2f7ff;color:#245da9;border-radius:8px;padding:5px 8px;font-size:9px;font-weight:800;cursor:pointer}
.pb-backdrop{position:fixed;inset:0;background:rgba(20,31,48,.34);z-index:70;display:none;align-items:center;justify-content:center;padding:16px}.pb-backdrop.open{display:flex}.pb-modal{width:min(1180px,97vw);max-height:91vh;background:#fff;border-radius:16px;border:1px solid #dbe3ec;box-shadow:0 28px 80px rgba(14,29,50,.22);display:grid;grid-template-columns:300px minmax(0,1fr);overflow:hidden}.pb-backdrop.pb-page-surface{position:static;inset:auto;z-index:auto;width:100%;min-height:calc(100vh - 92px);padding:0;background:transparent;display:block;align-items:stretch;justify-content:stretch}.pb-page-surface>.pb-modal{width:100%;max-width:none;max-height:none;min-height:calc(100vh - 92px);border-radius:10px;box-shadow:none}.pb-page-surface .pb-close{display:none}.pb-page-surface .pb-right{overflow:visible}
.pb-left{background:#f7f9fc;border-right:1px solid #e2e8f0;padding:13px;overflow:auto;min-width:0}.pb-page-surface .pb-left{position:sticky;top:0;align-self:start;max-height:calc(100vh - 92px)}.pb-left-head{display:flex;align-items:flex-start;justify-content:space-between;gap:8px;margin-bottom:9px}.pb-left-title b{display:block;font-size:12px;color:#2d435b}.pb-left-title span{display:block;margin-top:2px;font-size:8px;color:#8794a5}.pb-list-tools{display:grid;gap:6px;margin-bottom:8px}.pb-list-search{width:100%;border:1px solid #d9e2ec;background:#fff;border-radius:8px;padding:8px 9px;font:inherit;font-size:9px;outline:none}.pb-list-search:focus{border-color:#8db4ee;box-shadow:0 0 0 3px rgba(23,105,255,.07)}.pb-list-meta{font-size:8px;color:#8190a2;min-height:12px}.pb-list{display:grid;gap:6px}.pb-item{width:100%;border:1px solid #e3e9f0;border-radius:10px;padding:8px;background:#fff;cursor:pointer;text-align:left;display:grid;grid-template-columns:42px minmax(0,1fr);gap:8px;align-items:center;color:inherit}.pb-item:hover{border-color:#c8d7e8}.pb-item.active{border-color:#8fb7f3;background:#f3f7ff;box-shadow:0 0 0 1px rgba(23,105,255,.05)}.pb-item-thumb{width:42px;height:42px;border-radius:8px;background:#f1f4f8;display:grid;place-items:center;overflow:hidden;color:#9aa7b6;font-size:8px;font-weight:900}.pb-item-thumb img{width:100%;height:100%;object-fit:cover}.pb-item-copy{min-width:0}.pb-item-name{display:flex;gap:5px;align-items:center;min-width:0}.pb-item-name b{font-size:9.5px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:#294059}.pb-current{font-size:7px;color:#1769ff;background:#eaf2ff;border-radius:999px;padding:2px 5px;font-weight:900;flex:0 0 auto}.pb-item small{font-size:7.8px;color:#7b899a;display:block;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pb-item-progress{height:3px;background:#edf1f5;border-radius:999px;margin-top:5px;overflow:hidden}.pb-item-progress i{display:block;height:100%;background:#7da9e8;border-radius:inherit}.pb-list-empty{padding:18px 8px;text-align:center;border:1px dashed #d9e1ea;border-radius:10px;background:#fff;color:#7b899a;font-size:9px;line-height:1.55}.pb-list-pager{display:flex;align-items:center;justify-content:space-between;gap:6px;margin-top:8px}.pb-list-pager span{font-size:8px;color:#7d8b9c}.pb-pager-actions{display:flex;gap:4px}.pb-pager-actions button{border:1px solid #dce4ed;background:#fff;border-radius:7px;padding:5px 7px;font-size:8px;color:#50667e;cursor:pointer}.pb-pager-actions button:disabled{opacity:.4;cursor:default}
.pb-right{padding:15px 16px 0;overflow:auto;min-width:0}.pb-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.pb-kicker{font-size:8px;font-weight:900;color:#6f8299;letter-spacing:.08em}.pb-title-block{min-width:0}.pb-title-block h2{margin:3px 0 0;font-size:18px;color:#22384f;line-height:1.25;overflow-wrap:anywhere}.pb-title-block p{margin:4px 0 0;color:#77869a;font-size:9px;line-height:1.45}.pb-head-actions{display:flex;justify-content:flex-end;gap:6px;flex-wrap:wrap}.pb-close{border:0;background:#f0f4f8;border-radius:8px;width:30px;height:30px;cursor:pointer;color:#506276}.pb-summary{margin-top:12px;border:1px solid #e0e7ef;border-radius:12px;background:#fbfcfe;padding:11px;display:grid;grid-template-columns:112px minmax(0,1fr);gap:12px}.pb-product-image{height:104px;border:1px solid #e0e6ee;border-radius:9px;background:#fff;display:grid;place-items:center;overflow:hidden;color:#9aa7b6;font-size:8px;text-align:center;padding:8px}.pb-product-image img{width:100%;height:100%;object-fit:contain}.pb-summary-copy{min-width:0;display:grid;align-content:start;gap:8px}.pb-summary-top{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.pb-summary-name b{font-size:13px;color:#263c54;display:block;overflow-wrap:anywhere}.pb-summary-name span{display:block;font-size:8px;color:#7b8a9c;margin-top:2px}.pb-summary-status{display:flex;gap:5px;align-items:center;flex-wrap:wrap;justify-content:flex-end}.pb-badge{font-size:7.5px;padding:3px 6px;border-radius:999px;background:#eef3f8;color:#63758a;font-weight:850}.pb-badge.current{background:#e9f2ff;color:#1769ff}.pb-facts{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px}.pb-fact{border:1px solid #e7ecf2;background:#fff;border-radius:8px;padding:7px;min-width:0}.pb-fact span{display:block;color:#8895a5;font-size:7px}.pb-fact b{display:block;color:#314962;font-size:9px;margin-top:2px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pb-completion-row{display:grid;grid-template-columns:auto minmax(90px,1fr) auto;gap:8px;align-items:center}.pb-completion-row span,.pb-completion-row b{font-size:8px;color:#64788f}.pb-completion-track{height:5px;background:#e9eef4;border-radius:999px;overflow:hidden}.pb-completion-track i{display:block;height:100%;background:#4e8ee6;border-radius:inherit}
.pb-form{margin-top:12px}.pb-form-section{border:1px solid #e2e8ef;border-radius:11px;background:#fff;margin-bottom:10px;overflow:hidden}.pb-section-head{padding:10px 11px 8px;border-bottom:1px solid #edf1f5;background:#fbfcfd}.pb-section-head h3{margin:0;font-size:10.5px;color:#31485f}.pb-section-head p{margin:3px 0 0;font-size:8px;color:#8290a1;line-height:1.45}.pb-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;padding:11px}.pb-field{display:grid;gap:4px;min-width:0}.pb-field.span2{grid-column:span 2}.pb-field.full{grid-column:1/-1}.pb-field label{font-size:8.5px;color:#66778b;font-weight:800}.pb-field label em{font-style:normal;color:#a0a9b4;font-weight:600}.pb-field input,.pb-field textarea,.pb-field select{width:100%;border:1px solid #d9e2ec;border-radius:8px;padding:8px 9px;font:inherit;font-size:9.5px;outline:none;background:#fff;color:#253b52}.pb-field textarea{min-height:72px;resize:vertical;line-height:1.5}.pb-field textarea.compact{min-height:54px}.pb-field input:focus,.pb-field textarea:focus,.pb-field select:focus{border-color:#7fa9e7;box-shadow:0 0 0 3px rgba(23,105,255,.07)}.pb-field .hint{font-size:7.5px;color:#94a0af;line-height:1.4}.pb-safety{margin:0 11px 11px;border:1px solid #eadfca;background:#fffaf1;border-radius:8px;padding:8px 9px;color:#7b6642;font-size:8px;line-height:1.45}.pb-note{margin:0 0 10px;border:1px solid #dfe7ef;background:#f8fafc;color:#697a8e;border-radius:9px;padding:8px 9px;font-size:8px;line-height:1.5}.pb-foot{position:sticky;bottom:0;margin:12px -16px 0;padding:10px 16px;background:rgba(255,255,255,.98);border-top:1px solid #e3e9f0;display:flex;gap:7px;align-items:center;justify-content:space-between;z-index:4}.pb-foot-left,.pb-foot-right{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.pb-save-state{font-size:8px;color:#7c8a9b}.pb-save-state.dirty{color:#9b6a23}.pb-save-state.saved{color:#317155}.pb-danger{border:1px solid #e7c9cd;background:#fff;color:#a24650;border-radius:8px;padding:7px 9px;font-size:9px;font-weight:800;cursor:pointer}
@media(max-width:1100px){.pb-modal{grid-template-columns:260px minmax(0,1fr)}.pb-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.pb-field.span2{grid-column:1/-1}.pb-facts{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:760px){.pb-modal{grid-template-columns:1fr}.pb-left{max-height:250px;border-right:0;border-bottom:1px solid #e1e8f1}.pb-page-surface .pb-left{position:static;max-height:260px}.pb-head{display:grid}.pb-head-actions{justify-content:flex-start}.pb-summary{grid-template-columns:82px minmax(0,1fr)}.pb-product-image{height:82px}.pb-grid{grid-template-columns:1fr}.pb-field.span2,.pb-field.full{grid-column:auto}.pb-facts{grid-template-columns:1fr 1fr}.pb-bar{align-items:flex-start;flex-direction:column}.pb-actions{width:100%}.pb-foot{align-items:flex-start;flex-direction:column}.pb-foot-right{width:100%;justify-content:flex-end}}
`;document.head.appendChild(s)}
function installBar(){const search=$('.search');if(!search||$('#pbBar'))return;const box=document.createElement('section');box.id='pbBar';box.className='pb-bar';search.before(box);renderBar()}
function renderBar(message=''){const box=$('#pbBar');if(!box)return;const b=active();if(!b){box.innerHTML=`<div class="pb-main"><div class="pb-mark">产品</div><div class="pb-copy"><b>还没有常用产品资料</b><small>先建立一个真实产品，后续找客户、开发信、产品目录和单据都直接复用。</small></div></div><div class="pb-actions"><button class="pb-mini primary" id="pbManage">建立产品资料</button></div>`;$('#pbManage').onclick=openManager;return}const brief=core.campaignBrief(b,{country:$('#country')?.value||'',buyerType:$('#buyerType')?.value||''}),img=imageOf(b);box.innerHTML=`<div class="pb-main"><div class="pb-mark">${img?`<img src="${esc(img)}" alt="">`:'产品'}</div><div class="pb-copy"><b>${esc(b.name||'未命名产品')}${b.sku?` · ${esc(b.sku)}`:''}</b><small>${message?esc(message):esc([b.spec,b.moq?`MOQ ${b.moq}`:'',b.lead_time?`交期 ${b.lead_time}`:''].filter(Boolean).join(' · ')||'当前产品资料已启用')}</small><div class="pb-campaign"><span style="font-size:8px;color:#7d8b9b;font-weight:800">当前开发重点</span><div class="pb-chips">${brief.selling_angles.slice(0,4).map(x=>`<span class="pb-chip">${esc(x)}</span>`).join('')||'<span class="pb-chip">可继续补充产品卖点</span>'}</div></div></div></div><div class="pb-actions"><span class="pb-progress">完整度 ${core.completion(b)}%</span><button class="pb-mini" id="pbUseSearch">带入找客户</button><button class="pb-mini" id="pbManage">编辑产品</button></div>`;const barImg=box.querySelector('.pb-mark img');if(barImg)barImg.onerror=()=>{barImg.parentElement.textContent='产品'};$('#pbManage').onclick=openManager;$('#pbUseSearch').onclick=()=>{const k=$('#keyword');if(k){k.value=core.searchKeyword(b);k.focus()}renderBar('已把产品关键词带入找客户')}}
function modal(){if($('#pbBackdrop'))return;const d=document.createElement('div');d.id='pbBackdrop';d.className='pb-backdrop';d.innerHTML=`<div class="pb-modal">
<aside class="pb-left"><div class="pb-left-head"><div class="pb-left-title"><b>产品列表</b><span id="pbListCount">0 个产品</span></div><button type="button" class="pb-mini" id="pbNew">＋ 新建</button></div><div class="pb-list-tools"><input id="pbListSearch" class="pb-list-search" type="search" placeholder="搜索名称 / SKU / 分类 / 规格"><span id="pbListMeta" class="pb-list-meta"></span></div><div class="pb-list" id="pbList"></div><div class="pb-list-pager"><span id="pbListPageText">第 1 / 1 页</span><div class="pb-pager-actions"><button type="button" id="pbListPrev">上一页</button><button type="button" id="pbListNext">下一页</button></div></div></aside>
<section class="pb-right"><div class="pb-head"><div class="pb-title-block"><div class="pb-kicker">PRODUCT MASTER</div><h2 id="pbEditorTitle">产品资料</h2><p id="pbEditorMeta">长期可复用的产品事实；客户临时要求继续留在客户或询盘里。</p></div><div class="pb-head-actions"><button type="button" class="pb-mini" id="pbUseSelected">用于找客户</button><button type="button" class="pb-mini" id="pbCatalog">制作目录</button><button type="button" class="pb-mini primary" id="pbNewTop">＋ 新建产品</button><button type="button" class="pb-close" id="pbClose" aria-label="关闭">×</button></div></div>
<div class="pb-summary"><div class="pb-product-image" id="pbImagePreview">暂无产品图片</div><div class="pb-summary-copy"><div class="pb-summary-top"><div class="pb-summary-name"><b id="pbSummaryName">新产品</b><span id="pbSummaryMeta">填写名称、SKU 与规格后更容易快速识别。</span></div><div class="pb-summary-status"><span class="pb-badge" id="pbSummarySource">手动资料</span><span class="pb-badge current" id="pbSummaryCurrent" hidden>当前产品</span></div></div><div class="pb-facts"><div class="pb-fact"><span>参考价</span><b id="pbFactPrice">—</b></div><div class="pb-fact"><span>MOQ</span><b id="pbFactMoq">—</b></div><div class="pb-fact"><span>交期</span><b id="pbFactLead">—</b></div><div class="pb-fact"><span>包装 / 箱规</span><b id="pbFactPack">—</b></div></div><div class="pb-completion-row"><span>资料完整度</span><div class="pb-completion-track"><i id="pbCompletionBar" style="width:0%"></i></div><b id="pbCompletionText">0%</b></div></div></div>
<form id="pbForm" class="pb-form">
<section class="pb-form-section"><div class="pb-section-head"><h3>基础资料</h3><p>先把产品识别、图片和核心规格整理完整；这些字段会被找客户、产品目录和正式单据复用。</p></div><div class="pb-grid"><div class="pb-field span2"><label>产品名称</label><input data-pbf="name" autocomplete="off" placeholder="例如：304 不锈钢铰链"></div><div class="pb-field"><label>产品编号 / SKU / 型号</label><input data-pbf="sku" autocomplete="off"></div><div class="pb-field"><label>分类</label><input data-pbf="category" autocomplete="off"></div><div class="pb-field"><label>系列</label><input data-pbf="series" autocomplete="off"></div><div class="pb-field"><label>产品尺寸</label><input data-pbf="dimensions" placeholder="例如 100 × 75 × 2 mm"></div><div class="pb-field full"><label>主图地址 <em>产品目录可直接复用</em></label><input data-pbf="image_url" type="url" placeholder="https://…"></div><div class="pb-field full"><label>规格 / 核心参数</label><textarea data-pbf="spec" placeholder="材料、尺寸、结构、表面处理、关键性能等"></textarea></div></div></section>
<section class="pb-form-section"><div class="pb-section-head"><h3>报价参考</h3><p>这里是内部参考与目录展示依据；正式报价、PI、合同和 CI 的成交单价仍必须人工确认。</p></div><div class="pb-grid"><div class="pb-field"><label>参考单价</label><input data-pbf="price" inputmode="decimal" placeholder="例如 2.85"></div><div class="pb-field"><label>币种</label><input data-pbf="currency" list="pbCurrencyList" placeholder="USD"></div><div class="pb-field"><label>计价单位</label><input data-pbf="unit" list="pbUnitList" placeholder="PCS"></div><div class="pb-field span2"><label>参考价 / 价格区间</label><input data-pbf="price_range" placeholder="例如 USD 2.80–3.20 / PCS"></div><div class="pb-field"><label>起订量 MOQ</label><input data-pbf="moq" placeholder="例如 500 PCS"></div><div class="pb-field"><label>常用交期</label><input data-pbf="lead_time" placeholder="例如 25–30 天"></div></div><div class="pb-safety">价格边界：产品参考价只用于产品资料、开发上下文和目录展示核对，系统不会自动把它写入正式单据价格。</div></section>
<section class="pb-form-section"><div class="pb-section-head"><h3>客户开发资料</h3><p>只填写确认过、可以长期重复使用的事实。客户自己的临时要求不要写进产品主数据。</p></div><div class="pb-grid"><div class="pb-field full"><label>找客户关键词 <em>每行一个或用分号分隔</em></label><textarea class="compact" data-pbf="target_keywords" placeholder="stainless steel hinge&#10;OEM hinge&#10;custom size hinge"></textarea></div><div class="pb-field full"><label>认证 / 资质 <em>每行一项</em></label><textarea class="compact" data-pbf="certifications"></textarea></div><div class="pb-field full"><label>产品卖点 <em>每行一项</em></label><textarea data-pbf="differentiators"></textarea></div><div class="pb-field full"><label>客户案例 <em>只写真实可公开内容</em></label><textarea data-pbf="customer_cases"></textarea></div><div class="pb-field full"><label>公司优势 / 供应能力</label><textarea data-pbf="company_facts"></textarea></div><div class="pb-field full"><label>允许对客户表达的承诺 / 事实</label><textarea data-pbf="allowed_claims"></textarea></div><div class="pb-field full"><label>不允许自动承诺的内容</label><textarea data-pbf="restricted_claims" placeholder="例如：未经确认不得承诺独家、账期、认证通过、固定交期"></textarea></div></div></section>
<section class="pb-form-section"><div class="pb-section-head"><h3>报关与贸易</h3><p>用于单据准备和贸易核对；不确定的编码或描述可以先留空，避免猜测。</p></div><div class="pb-grid"><div class="pb-field"><label>HS 编码</label><input data-pbf="hs_code"></div><div class="pb-field"><label>原产国 / 地区</label><input data-pbf="country_of_origin"></div><div class="pb-field"><label>供应商 / 工厂</label><input data-pbf="supplier_name"></div><div class="pb-field full"><label>报关品名 / Customs Description</label><textarea class="compact" data-pbf="customs_description"></textarea></div></div></section>
<section class="pb-form-section"><div class="pb-section-head"><h3>包装与物流</h3><p>记录稳定的包装结构与重量体积，方便目录、装箱和物流核对。</p></div><div class="pb-grid"><div class="pb-field"><label>包装类型</label><input data-pbf="package_type" placeholder="例如 彩盒 + 外箱"></div><div class="pb-field"><label>箱规</label><input data-pbf="carton_size" placeholder="例如 52 × 38 × 31 cm"></div><div class="pb-field"><label>每箱数量</label><input data-pbf="qty_per_carton"></div><div class="pb-field"><label>净重 N.W.</label><input data-pbf="net_weight"></div><div class="pb-field"><label>毛重 G.W.</label><input data-pbf="gross_weight"></div><div class="pb-field"><label>装箱体积 CBM</label><input data-pbf="cbm"></div><div class="pb-field full"><label>唛头 / Shipping Marks</label><textarea class="compact" data-pbf="shipping_marks"></textarea></div></div></section>
<section class="pb-form-section"><div class="pb-section-head"><h3>媒体、来源与内部备注</h3><p>保留产品来源和演示资料，方便团队核对；内部备注不会作为客户承诺自动输出。</p></div><div class="pb-grid"><div class="pb-field full"><label>产品来源链接</label><input data-pbf="source_url" type="url" placeholder="https://…"></div><div class="pb-field full"><label>产品视频链接</label><input data-pbf="video_url" type="url" placeholder="https://…"></div><div class="pb-field full"><label>内部备注</label><textarea data-pbf="notes"></textarea></div></div></section>
<div class="pb-note">产品资料保存长期稳定事实；客户要求、背调结论、询盘数量、成交价格和当前跟进状态继续由各自 Owner 管理，避免同一事实出现多套版本。</div>
<datalist id="pbCurrencyList"><option value="USD"><option value="EUR"><option value="CNY"><option value="GBP"><option value="JPY"><option value="AUD"><option value="CAD"></datalist><datalist id="pbUnitList"><option value="PCS"><option value="SET"><option value="PAIR"><option value="KG"><option value="M"><option value="M2"><option value="CTN"></datalist>
<div class="pb-foot"><div class="pb-foot-left"><button type="button" class="pb-danger" id="pbDelete">删除产品</button><span id="pbSaveState" class="pb-save-state">未修改</span></div><div class="pb-foot-right"><button type="button" class="pb-mini" id="pbActivate">设为当前产品</button><button class="pb-mini primary" type="submit">保存产品资料</button></div></div></form></section></div>`;document.body.appendChild(d);
$('#pbClose').onclick=closeManager;d.onclick=e=>{if(e.target===d&&surface!=='page')closeManager()};$('#pbNew').onclick=newProduct;$('#pbNewTop').onclick=newProduct;$('#pbDelete').onclick=removeCurrent;$('#pbActivate').onclick=activateSelected;$('#pbUseSelected').onclick=useSelectedForSearch;$('#pbCatalog').onclick=openCatalog;$('#pbForm').onsubmit=e=>{e.preventDefault();saveForm()};
$('#pbListSearch').addEventListener('input',e=>{listQuery=clean(e.target.value).toLowerCase();listPage=1;renderList()});$('#pbListPrev').onclick=()=>{if(listPage>1){listPage-=1;renderList()}};$('#pbListNext').onclick=()=>{listPage+=1;renderList()};
$('#pbForm').addEventListener('input',()=>{dirty=true;saveNote='';renderSaveState();renderDraftSummary()});}
function setSurface(mode='modal',target=null){modal();const root=$('#pbBackdrop');if(mode==='page'){surface='page';pageHost=target||pageHost;if(pageHost&&root.parentElement!==pageHost)pageHost.appendChild(root);root.classList.add('pb-page-surface','open');document.body.style.overflow='';renderList();renderDraftSummary();return root}surface='modal';pageHost=null;if(root.parentElement!==document.body)document.body.appendChild(root);root.classList.remove('pb-page-surface');root.classList.add('open');renderList();renderDraftSummary();return root}
function productSearchText(x){return [x?.name,x?.sku,x?.category,x?.series,x?.spec,x?.hs_code].map(clean).join(' ').toLowerCase()}
function orderedRows(){const rows=read(),aid=String(activeId());return [...rows].sort((a,b)=>{const ac=String(a.id)===aid,bc=String(b.id)===aid;if(ac!==bc)return ac?-1:1;return (Date.parse(b.updated_at||0)||0)-(Date.parse(a.updated_at||0)||0)})}
function renderList(){const box=$('#pbList');if(!box)return;const rows=orderedRows(),filtered=listQuery?rows.filter(x=>productSearchText(x).includes(listQuery)):rows;const pages=Math.max(1,Math.ceil(filtered.length/LIST_PAGE_SIZE));listPage=Math.max(1,Math.min(listPage,pages));const pageRows=filtered.slice((listPage-1)*LIST_PAGE_SIZE,listPage*LIST_PAGE_SIZE);$('#pbListCount').textContent=`${rows.length} 个产品`;$('#pbListMeta').textContent=listQuery?`找到 ${filtered.length} 个匹配产品`:`每页 ${LIST_PAGE_SIZE} 个，搜索可快速定位`;$('#pbListPageText').textContent=`第 ${listPage} / ${pages} 页`;$('#pbListPrev').disabled=listPage<=1;$('#pbListNext').disabled=listPage>=pages;if(!pageRows.length){box.innerHTML=`<div class="pb-list-empty">${rows.length?'没有匹配的产品。可以换名称、SKU、分类或规格搜索。':'还没有产品资料。先新建一个真实产品。'}</div>`;return}box.innerHTML=pageRows.map(x=>{const id=String(x.id||''),pct=core.completion(x),img=imageOf(x);return `<button type="button" class="pb-item ${id===String(editId)?'active':''}" data-pbid="${esc(id)}"><span class="pb-item-thumb">${img?`<img src="${esc(img)}" alt="">`:'产品'}</span><span class="pb-item-copy"><span class="pb-item-name"><b>${esc(x.name||'未命名产品')}</b>${id===String(activeId())?'<span class="pb-current">当前</span>':''}</span><small>${esc([x.sku,x.category,x.series].filter(Boolean).join(' · ')||'SKU / 分类待补充')}</small><small>${esc([x.moq?`MOQ ${x.moq}`:'',x.lead_time?`交期 ${x.lead_time}`:''].filter(Boolean).join(' · ')||'关键贸易资料待补充')} · ${pct}%</small><span class="pb-item-progress"><i style="width:${pct}%"></i></span></span></button>`}).join('');box.querySelectorAll('.pb-item-thumb img').forEach(img=>img.onerror=()=>{img.parentElement.textContent='产品'});box.querySelectorAll('[data-pbid]').forEach(x=>x.onclick=()=>selectProduct(x.dataset.pbid))}
function canDiscardDirty(){return !dirty||confirm('当前产品有未保存的修改，继续后这些修改会丢失。是否继续？')}
function selectProduct(id){if(!canDiscardDirty())return;const b=read().find(r=>String(r.id)===String(id));if(b){editId=b.id;fill(b)}}
function blankProduct(){const b=core.normalize({name:'',source:'manual'});b.id='';b.local_product_id='';return b}
function newProduct(){if(!canDiscardDirty())return;listQuery='';listPage=1;if($('#pbListSearch'))$('#pbListSearch').value='';fill(blankProduct());const name=document.querySelector('[data-pbf="name"]');setTimeout(()=>name?.focus(),0)}
function fill(b){editId=b?.id||'';document.querySelectorAll('[data-pbf]').forEach(el=>{const k=el.dataset.pbf,v=b?.[k];el.value=Array.isArray(v)?v.join('\n'):(v??'')});dirty=false;saveNote='';renderSaveState();renderList();renderDraftSummary()}
function formValues(){const raw={};document.querySelectorAll('[data-pbf]').forEach(el=>raw[el.dataset.pbf]=el.value);for(const key of ['certifications','differentiators','customer_cases','company_facts','target_keywords','allowed_claims','restricted_claims'])raw[key]=lines(raw[key]);return raw}
function formBrain(){const current=read().find(x=>String(x.id)===String(editId))||{},raw={...current,...formValues()},normalized=core.normalize({...raw,id:current.id||undefined,brain_id:current.id||undefined,local_product_id:current.local_product_id||'',created_at:current.created_at||''});normalized.image_url=clean(raw.image_url||current.image_url);if(Array.isArray(current.images))normalized.images=current.images;return normalized}
function renderSaveState(){const node=$('#pbSaveState');if(!node)return;node.classList.toggle('dirty',dirty);node.classList.toggle('saved',!dirty&&!!saveNote);node.textContent=dirty?'有未保存修改':(saveNote||'未修改')}
function draftForSummary(){const current=read().find(x=>String(x.id)===String(editId))||{},raw={...current,...formValues()};return raw}
function renderDraftSummary(){if(!$('#pbSummaryName'))return;const b=draftForSummary(),name=clean(b.name)||'新产品',sku=clean(b.sku),category=clean(b.category),series=clean(b.series),pct=core.completion(b),img=imageOf(b),rawPrice=clean(b.price),price=clean(b.price_range)||(rawPrice?`${clean(b.currency)||'USD'} ${rawPrice}${clean(b.unit)?` / ${clean(b.unit)}`:''}`:'—');$('#pbEditorTitle').textContent=name;$('#pbEditorMeta').textContent=[sku,category,series].filter(Boolean).join(' · ')||'长期可复用的产品事实；客户临时要求继续留在客户或询盘里。';$('#pbSummaryName').textContent=name;$('#pbSummaryMeta').textContent=[sku?`SKU ${sku}`:'',clean(b.spec)].filter(Boolean).join(' · ')||'填写名称、SKU 与规格后更容易快速识别。';$('#pbSummarySource').textContent=clean(b.source)==='manual'?'手动资料':'已同步资料';const current=$('#pbSummaryCurrent');current.hidden=!editId||String(editId)!==String(activeId());$('#pbFactPrice').textContent=price;$('#pbFactMoq').textContent=clean(b.moq)||'—';$('#pbFactLead').textContent=clean(b.lead_time)||'—';$('#pbFactPack').textContent=[clean(b.package_type),clean(b.carton_size)].filter(Boolean).join(' · ')||'—';$('#pbCompletionText').textContent=`${pct}%`;$('#pbCompletionBar').style.width=`${pct}%`;const preview=$('#pbImagePreview');preview.innerHTML=img?`<img src="${esc(img)}" alt="${esc(name)}">`:'暂无产品图片';const image=preview.querySelector('img');if(image)image.onerror=()=>{preview.textContent='图片暂时无法访问'};const activate=$('#pbActivate');if(activate){const isCurrent=!!editId&&String(editId)===String(activeId());activate.disabled=!editId||isCurrent;activate.textContent=isCurrent?'当前产品':'设为当前产品'};const canUse=!!editId&&!dirty;$('#pbUseSelected').disabled=!canUse;$('#pbCatalog').disabled=dirty}
function saveForm(){const b=formBrain();if(!b.name)return alert('先填写产品名称');const rows=core.upsert(read(),b);write(rows);const hit=(rows.find(x=>String(x.local_product_id)&&String(x.local_product_id)===String(b.local_product_id))||rows.find(x=>clean(x.sku)&&clean(x.sku).toLowerCase()===clean(b.sku).toLowerCase())||rows.find(x=>clean(x.name).toLowerCase()===clean(b.name).toLowerCase())||b);editId=hit.id;if(!activeId())localStorage.setItem(ACTIVE,String(editId));dirty=false;saveNote='已保存';fill(read().find(x=>String(x.id)===String(editId))||hit);saveNote='已保存';renderSaveState();renderBar('产品资料已保存，后续找客户、目录和单据会继续复用');window.HUIDIBeginnerFlow?.refresh?.()}
function removeCurrent(){if(!editId)return;if(!confirm('删除这份产品资料？不会删除正式单据，也不会删除本地工作台里的原始商品资料。'))return;const rows=read().filter(x=>String(x.id)!==String(editId));write(rows);if(String(activeId())===String(editId))localStorage.removeItem(ACTIVE);dirty=false;saveNote='';editId=rows[0]?.id||'';if(rows[0])fill(rows[0]);else fill(blankProduct());renderBar();window.HUIDIBeginnerFlow?.refresh?.()}
function activateSelected(){if(!editId)return;if(dirty)return alert('请先保存当前修改，再设为当前产品');setActive(editId);saveNote='已设为当前产品';renderSaveState()}
function useSelectedForSearch(){if(!editId)return;if(dirty)return alert('请先保存当前修改，再用于找客户');const b=read().find(x=>String(x.id)===String(editId));if(!b)return;setActive(editId);const nav=document.querySelector('[data-huidi-nav="find"]');nav?.click();setTimeout(()=>{const k=$('#keyword');if(k){k.value=core.searchKeyword(b);k.dispatchEvent(new Event('input',{bubbles:true}));k.focus()}renderBar('已把当前产品关键词带入找客户')},50)}
function openCatalog(){if(dirty)return alert('请先保存当前修改，再制作产品目录');if(window.HUIDIWorkspacePages?.open){window.HUIDIWorkspacePages.open('catalog');return}document.querySelector('[data-huidi-catalog]')?.click()}
function prepareManager(){modal();const b=active()||read()[0]||blankProduct();editId=b.id||'';fill(b);return $('#pbBackdrop')}
function openManager(){prepareManager();if(surface==='page'&&pageHost?.isConnected)setSurface('page',pageHost);else setSurface('modal')}
async function mount(target){if(!target)throw new Error('产品资料页面缺少挂载位置');prepareManager();setSurface('page',target);return $('#pbBackdrop')}
function unmount(){const root=$('#pbBackdrop');if(!root)return;if(root.parentElement!==document.body)document.body.appendChild(root);root.classList.remove('open','pb-page-surface');surface='modal';pageHost=null;document.body.style.overflow=''}
function closeManager(){if(surface!=='page'&&dirty&&!confirm('当前产品有未保存的修改，仍要关闭吗？'))return;$('#pbBackdrop')?.classList.remove('open')}
function installDraftUse(){const field=$('#productSummary');if(!field||$('#pbUseDraft'))return;const btn=document.createElement('button');btn.type='button';btn.id='pbUseDraft';btn.className='pb-inline-use';btn.textContent='带入当前产品资料';btn.onclick=()=>{const b=active();if(!b)return openManager();field.value=core.facts(b)};field.parentElement.appendChild(btn)}
function importHash(){try{const raw=String(location.hash||'').replace(/^#/,'');if(!raw)return;const p=new URLSearchParams(raw),encoded=p.get('product');if(!encoded)return;const input=core.decodeBase64Url(encoded),b=core.normalize(input);if(!b.name)throw new Error('产品缺少名称');const rows=core.upsert(read(),b);write(rows);const hit=rows.find(x=>(b.local_product_id&&String(x.local_product_id)===String(b.local_product_id))||(b.sku&&clean(x.sku).toLowerCase()===clean(b.sku).toLowerCase()))||rows[0];setActive(hit.id);history.replaceState(null,'',location.pathname+location.search);setTimeout(()=>{renderBar('已从本地工作台带入产品资料，并设为当前产品');const k=$('#keyword');if(k&&!clean(k.value))k.value=core.searchKeyword(hit);window.HUIDIBeginnerFlow?.refresh?.()},0)}catch(e){console.warn('[HUIDI Product] import failed',e)}}
function bindCampaign(){document.addEventListener('click',e=>{if(e.target.closest('#searchBtn')){const b=active(),k=$('#keyword');if(b&&k&&!clean(k.value))k.value=core.searchKeyword(b)}if(e.target.closest('[data-open]'))setTimeout(installDraftUse,0)},true);['country','buyerType'].forEach(id=>$('#'+id)?.addEventListener('input',()=>renderBar()))}
css();installBar();modal();installDraftUse();bindCampaign();importHash();renderList();
window.HUIDIProductBrain=Object.freeze({list:read,active,open:openManager,mount,unmount,surface:()=>surface,facts:()=>core.facts(active()),campaign:()=>core.campaignBrief(active(),{country:$('#country')?.value||'',buyerType:$('#buyerType')?.value||''})});
})();
