(()=>{'use strict';
if(window.HUIDISequenceUI)return;
const $=s=>document.querySelector(s),clean=v=>String(v??'').trim(),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
let leadId='';
const friendly=e=>window.HUIDIPlainLanguage?.message?.(e?.message||e)||String(e?.message||e||'暂时无法完成，请稍后重试。');
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});if(!r.ok){let msg=await r.text();try{msg=JSON.parse(msg).detail||msg}catch(_){}throw new Error(msg||r.statusText)}return r.json()}
function css(){if($('#seqCss'))return;const s=document.createElement('style');s.id='seqCss';s.textContent=`.sq-back{position:fixed;inset:0;background:rgba(15,27,45,.36);z-index:125;display:none;align-items:center;justify-content:center;padding:18px}.sq-back.open{display:flex}.sq-modal{width:min(980px,96vw);max-height:90vh;background:#fff;border:1px solid #dce4ee;border-radius:17px;box-shadow:0 28px 80px rgba(15,31,50,.24);display:grid;grid-template-rows:auto minmax(0,1fr);overflow:hidden}.sq-head{padding:16px 17px 10px;display:flex;justify-content:space-between;gap:12px}.sq-head h2{margin:0;font-size:19px}.sq-head p{margin:4px 0 0;color:#728096;font-size:10px}.sq-close{border:0;background:#f1f4f7;border-radius:9px;width:33px;height:33px;font-size:19px;cursor:pointer}.sq-main{padding:0 17px 17px;overflow:auto}.sq-grid{display:grid;grid-template-columns:1.05fr .95fr;gap:12px}.sq-card{border:1px solid #e0e7ef;border-radius:12px;background:#fbfcfe;padding:12px}.sq-card h3{margin:0 0 7px;font-size:12px}.sq-note{font-size:9px;color:#718096;line-height:1.55}.sq-list{display:grid;gap:7px;margin-top:8px}.sq-item{border:1px solid #e1e7ee;border-radius:10px;background:#fff;padding:9px}.sq-item b{display:block;font-size:10px;color:#334c69}.sq-item span,.sq-item small{display:block;margin-top:3px;font-size:8.5px;color:#788698;line-height:1.45}.sq-btn{border:1px solid #d7e1ec;background:#fff;border-radius:8px;padding:7px 9px;font-size:9px;font-weight:850;color:#36516f;cursor:pointer}.sq-btn.primary{background:#1d63e9;border-color:#1d63e9;color:#fff}.sq-row{display:flex;gap:6px;align-items:center;flex-wrap:wrap;margin-top:8px}.sq-field{display:grid;gap:4px;margin-top:8px}.sq-field label{font-size:9px;font-weight:800;color:#64758a}.sq-field input,.sq-field select,.sq-field textarea{border:1px solid #d9e2ec;border-radius:8px;padding:8px 9px;font:inherit;font-size:9px;background:#fff}.sq-step{border-top:1px solid #e8edf3;margin-top:10px;padding-top:10px}.sq-step-head{display:flex;justify-content:space-between;gap:8px;align-items:center}.sq-badge{display:inline-block;border-radius:999px;padding:3px 6px;font-size:8px;background:#eef5ff;color:#275fa9}.sq-badge.ok{background:#eaf7f0;color:#14734f}.sq-empty{padding:18px 4px;text-align:center;color:#8794a4;font-size:9px}.sq-inline{margin-top:7px;border:1px solid #cdddf2;background:#f5f9ff;color:#2f609d;border-radius:8px;padding:6px 8px;font-size:9px;font-weight:850;cursor:pointer}@media(max-width:760px){.sq-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function shell(){if($('#sqBack'))return;const d=document.createElement('div');d.id='sqBack';d.className='sq-back';d.innerHTML='<div class="sq-modal"><div class="sq-head"><div><h2>自动跟进</h2><p>一次确认整套邮件内容和时间；客户回复、退订或进入正式询盘后，后续邮件会自动停止。</p></div><button class="sq-close" data-sq-close>×</button></div><main class="sq-main" id="sqMain"></main></div>';document.body.appendChild(d);d.onclick=e=>{if(e.target===d)close()};$('[data-sq-close]').onclick=close}
function close(){$('#sqBack')?.classList.remove('open')}
function open(currentLead=''){if(currentLead)leadId=String(currentLead);shell();$('#sqBack').classList.add('open');render()}
async function render(){const main=$('#sqMain');main.innerHTML='<div class="sq-empty">正在读取自动跟进…</div>';try{let [templates,boxes,enrollments]=await Promise.all([api('/api/mail/sequences'),api('/api/mail/accounts'),api('/api/mail/sequence-enrollments')]);if(!templates.length){await api('/api/mail/sequences/default',{method:'POST'});templates=await api('/api/mail/sequences')}const connected=boxes.filter(x=>x.enabled);main.innerHTML=`<div class="sq-grid"><section class="sq-card"><h3>跟进内容</h3><div class="sq-note">先检查每一次要发什么。只有点“确认这套内容”后，才可以给客户启用。</div><div class="sq-list" id="sqTemplates">${templates.map(templateHtml).join('')}</div></section><section class="sq-card"><h3>${leadId?'给当前客户启用':'正在自动跟进'}</h3>${leadId?enrollBox(templates,connected):'<div class="sq-note">从客户详情里也可以直接启用自动跟进。</div>'}<div class="sq-list" id="sqEnrollments">${enrollments.length?enrollments.map(enrollmentHtml).join(''):'<div class="sq-empty">当前没有自动跟进中的客户。</div>'}</div></section></div>`;bindTemplates(templates);bindEnrollments();$('[data-sq-start]')?.addEventListener('click',startForLead)}catch(e){main.innerHTML=`<div class="sq-empty">${esc(friendly(e))}</div>`}}
function templateHtml(t){return `<div class="sq-item" data-template="${t.id}"><div class="sq-step-head"><b>${esc(t.name)}</b><span class="sq-badge ${t.approved?'ok':''}">${t.approved?'已确认':'待确认'}</span></div><span>${esc(t.description||'')}</span>${(t.steps||[]).map((s,i)=>`<div class="sq-step"><div class="sq-step-head"><b>第 ${i+1} 次</b><span class="sq-badge">${i===0&&Number(s.delay_hours||0)===0?'立即':`${Number(s.delay_hours||0)} 小时后`}</span></div><div class="sq-field"><label>邮件主题</label><input data-step-subject="${i}" value="${esc(s.subject||'')}"></div><div class="sq-field"><label>邮件内容</label><textarea data-step-body="${i}" rows="4">${esc(s.body||'')}</textarea></div><div class="sq-field"><label>等待时间（小时）</label><input data-step-delay="${i}" type="number" min="0" max="2160" value="${Number(s.delay_hours||0)}"></div></div>`).join('')}<div class="sq-row"><button class="sq-btn primary" data-save-template="${t.id}">确认这套内容</button></div></div>`}
function enrollBox(ts,boxes){return `<div class="sq-field"><label>选择跟进内容</label><select id="sqTemplateSelect">${ts.filter(x=>x.approved&&x.enabled).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('')}</select></div><div class="sq-field"><label>发送邮箱</label><select id="sqMailboxSelect">${boxes.map(x=>`<option value="${x.id}">${esc(x.email)}${x.connection_state==='connected'?' · 已连接':''}</option>`).join('')}</select></div><div class="sq-row"><button class="sq-btn primary" data-sq-start ${!ts.some(x=>x.approved&&x.enabled)||!boxes.length?'disabled':''}>开始自动跟进</button></div><div class="sq-note">开始后会按你确认的内容发送。每次发送前仍会检查客户是否已经回复、退订或进入询盘。</div>`}
function enrollmentHtml(x){const state={active:'进行中',paused:'已暂停',stopped:'已停止',completed:'已完成'}[x.state]||'待处理';return `<div class="sq-item"><div class="sq-step-head"><b>${esc(x.company_name||'客户')}</b><span class="sq-badge ${x.state==='active'?'ok':''}">${esc(state)}</span></div><span>${esc(x.template_name)} · 已完成 ${Math.min(x.current_step,x.total_steps)}/${x.total_steps}</span><small>${x.next_at&&x.state==='active'?`下次：${esc(String(x.next_at).replace('T',' ').slice(0,16))}`:esc(x.stop_reason||friendly(x.last_error)||'')}</small>${['active','paused'].includes(x.state)?`<div class="sq-row">${x.state==='active'?`<button class="sq-btn" data-enroll-state="paused" data-enroll-id="${x.id}">暂停</button>`:`<button class="sq-btn" data-enroll-state="active" data-enroll-id="${x.id}">继续</button>`}<button class="sq-btn" data-enroll-state="stopped" data-enroll-id="${x.id}">停止</button></div>`:''}</div>`}
function bindTemplates(templates){document.querySelectorAll('[data-save-template]').forEach(btn=>btn.onclick=async()=>{const id=Number(btn.dataset.saveTemplate),t=templates.find(x=>x.id===id),box=btn.closest('[data-template]');if(!t||!box)return;const steps=(t.steps||[]).map((s,i)=>({delay_hours:Number(box.querySelector(`[data-step-delay="${i}"]`)?.value||0),subject:clean(box.querySelector(`[data-step-subject="${i}"]`)?.value),body:clean(box.querySelector(`[data-step-body="${i}"]`)?.value)}));if(steps.some(x=>!x.subject||!x.body))return alert('每一次都要填写邮件主题和内容');if(!confirm('确认这套跟进内容和发送时间？以后给客户启用时，会按这里的内容自动发送。'))return;try{await api('/api/mail/sequences/'+id,{method:'PUT',body:JSON.stringify({name:t.name,description:t.description||'',steps,confirm:true,enabled:true})});render()}catch(e){alert(friendly(e))}})}
function bindEnrollments(){document.querySelectorAll('[data-enroll-state]').forEach(btn=>btn.onclick=async()=>{try{await api(`/api/mail/sequence-enrollments/${btn.dataset.enrollId}/state`,{method:'POST',body:JSON.stringify({state:btn.dataset.enrollState})});render();window.HUIDIBeginnerFlow?.refresh?.()}catch(e){alert(friendly(e))}})}
async function startForLead(){const template_id=Number($('#sqTemplateSelect')?.value),mailbox_id=Number($('#sqMailboxSelect')?.value);if(!leadId||!template_id||!mailbox_id)return;if(!confirm('确认给这个客户开始自动跟进？客户一旦回复，后续邮件会自动停止。'))return;try{await api(`/api/leads/${leadId}/sequence`,{method:'POST',body:JSON.stringify({template_id,mailbox_id,confirm:true})});alert('已开始自动跟进');window.HUIDIBeginnerFlow?.refresh?.();render()}catch(e){alert(friendly(e))}}
function installInline(){const draft=$('#draftBox')?.closest('.section');if(!draft||$('#sqInline'))return;const b=document.createElement('button');b.id='sqInline';b.type='button';b.className='sq-inline';b.textContent='设置自动跟进';b.onclick=()=>open(leadId);draft.appendChild(b)}
function bind(){document.addEventListener('click',e=>{const o=e.target.closest('[data-open]');if(o){leadId=String(o.dataset.open||'');setTimeout(installInline,30)}const nav=e.target.closest('[data-huidi-sequences]');if(nav){e.preventDefault();open()}},true)}
function boot(){css();shell();bind();installInline()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.HUIDISequenceUI=Object.freeze({open});
})();