(()=>{'use strict';
if(window.HUIDITeamAccess)return;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let status=null,me=null,organization=null;
const friendly=e=>window.HUIDIPlainLanguage?.message?.(e?.message||e)||String(e?.message||e||'暂时无法完成，请稍后重试。');
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});if(!r.ok){let msg=await r.text();try{msg=JSON.parse(msg).detail||msg}catch(_){}throw new Error(msg||r.statusText)}return r.json()}
function css(){if($('#taCss'))return;const s=document.createElement('style');s.id='taCss';s.textContent=`.ta-btn{border:1px solid #d8e1ec;background:#fff;color:#36516f;border-radius:9px;padding:8px 10px;font-size:9px;font-weight:850;cursor:pointer}.ta-chip{display:inline-flex;align-items:center;gap:5px;border:1px solid #dce4ee;background:#fff;border-radius:999px;padding:5px 8px;font-size:8.5px;color:#52657c;cursor:pointer}.ta-back{position:fixed;inset:0;background:rgba(15,27,45,.44);z-index:190;display:none;align-items:center;justify-content:center;padding:18px}.ta-back.open{display:flex}.ta-modal{width:min(790px,94vw);max-height:88vh;overflow:auto;background:#fff;border:1px solid #dce4ee;border-radius:17px;box-shadow:0 30px 90px rgba(15,31,50,.28);padding:17px}.ta-modal h2{margin:0;font-size:19px}.ta-modal h3{margin:18px 0 4px;font-size:13px}.ta-modal p{margin:5px 0 14px;color:#738095;font-size:10px;line-height:1.55}.ta-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.ta-field{display:grid;gap:4px}.ta-field.full{grid-column:1/-1}.ta-field label{font-size:9px;font-weight:800;color:#62738a}.ta-field input,.ta-field select{height:36px;border:1px solid #d9e2ec;border-radius:9px;padding:0 9px;font:inherit;font-size:10px}.ta-row{display:flex;align-items:center;gap:7px;flex-wrap:wrap;margin-top:10px}.ta-primary{border:1px solid #1d63e9;background:#1d63e9;color:#fff;border-radius:9px;padding:8px 11px;font-size:9px;font-weight:850;cursor:pointer}.ta-list{display:grid;gap:7px;margin-top:12px}.ta-item{border:1px solid #e2e8ef;border-radius:10px;padding:9px 10px;display:flex;align-items:center;justify-content:space-between;gap:9px}.ta-item b{display:block;font-size:10px;color:#334c69}.ta-item span{display:block;margin-top:2px;font-size:8.5px;color:#788698}.ta-role{font-size:8px;border-radius:999px;padding:4px 6px;background:#eef4fb;color:#45627f}.ta-note{border:1px solid #e4e9ef;background:#f8fafc;border-radius:9px;padding:9px 10px;font-size:9px;color:#66778d;line-height:1.5}.ta-close{float:right;border:0;background:#f1f4f7;width:32px;height:32px;border-radius:9px;font-size:18px;cursor:pointer}.ta-divider{height:1px;background:#e7ecf2;margin:17px 0}.ta-login .ta-modal{width:min(430px,94vw)}@media(max-width:650px){.ta-grid{grid-template-columns:1fr}.ta-field.full{grid-column:auto}.ta-item{align-items:flex-start;flex-direction:column}}`;document.head.appendChild(s)}
function shell(){if($('#taBack'))return;const d=document.createElement('div');d.id='taBack';d.className='ta-back';d.innerHTML='<div class="ta-modal" id="taModal"></div>';document.body.appendChild(d);d.onclick=e=>{if(e.target===d&&me)d.classList.remove('open')}}
function roleName(role){return ({owner:'老板',admin:'管理员',sales:'业务员',viewer:'只读成员'})[role]||role}
function orgName(){return organization?.name||me?.organization?.name||'当前公司'}
function canManageCompanies(){return me?.role==='owner'&&Number(organization?.id||me?.organization_id||0)===1}
function ensureTop(){const top=$('.top');if(!top||$('#taTop'))return;const box=document.createElement('div');box.id='taTop';box.className='ta-chip';box.innerHTML='<span>单人使用</span>';box.onclick=()=>openTeam();top.appendChild(box)}
function topText(){const box=$('#taTop');if(!box)return;if(!status?.enabled){box.innerHTML='<span>单人使用</span>';return}if(!me){box.innerHTML='<span>团队 · 未登录</span>';return}box.innerHTML=`<span>${esc(orgName())} · ${esc(me.display_name||me.email)} · ${esc(roleName(me.role))}</span>`}
function openLogin(){shell();const back=$('#taBack');back.classList.add('open','ta-login');const m=$('#taModal');m.innerHTML=`<h2>登录 HUIDI</h2><p>登录后继续处理你所在公司的客户、邮件和业务。</p><div class="ta-field"><label>邮箱</label><input id="taEmail" type="email" autocomplete="username"></div><div class="ta-field" style="margin-top:9px"><label>密码</label><input id="taPassword" type="password" autocomplete="current-password"></div><div class="ta-row"><button class="ta-primary" data-ta-login>登录</button></div><div id="taLoginMsg" class="ta-note" style="display:none;margin-top:10px"></div>`;$('[data-ta-login]').onclick=login;$('#taPassword').onkeydown=e=>{if(e.key==='Enter')login()}}
async function login(){const msg=$('#taLoginMsg');try{const out=await api('/api/team/login',{method:'POST',body:JSON.stringify({email:$('#taEmail').value,password:$('#taPassword').value})});me=out.member;organization=out.member?.organization||null;$('#taBack').classList.remove('open','ta-login');topText();location.reload()}catch(e){msg.style.display='block';msg.textContent=friendly(e)}}
async function logout(){try{await api('/api/team/logout',{method:'POST',body:'{}'})}catch(_){}me=null;organization=null;topText();location.reload()}
async function openTeam(){if(!status?.enabled){shell();$('#taBack').classList.add('open');$('#taModal').innerHTML='<button class="ta-close" data-ta-close>×</button><h2>团队</h2><p>当前是单人使用。需要多人一起处理客户和订单时，请让管理员开启团队登录。</p><div class="ta-note">开启后可以设置老板、管理员、业务员和只读成员。不同公司的客户、邮件、产品和业务不会混在一起。</div>';$('[data-ta-close]').onclick=()=>$('#taBack').classList.remove('open');return}if(!me)return openLogin();shell();$('#taBack').classList.add('open');const m=$('#taModal');m.innerHTML=`<button class="ta-close" data-ta-close>×</button><h2>${esc(orgName())}</h2><p>${esc(me.display_name||me.email)} · ${esc(roleName(me.role))}</p><div class="ta-note">你现在看到和处理的客户、邮件、产品与业务都只属于当前公司。</div><div class="ta-row"><button class="ta-btn" data-ta-logout>退出登录</button></div><div id="taMembers"><div class="ta-note" style="margin-top:12px">正在读取成员…</div></div>${canManageCompanies()?'<div id="taOrganizations"><div class="ta-note" style="margin-top:14px">正在读取公司账号…</div></div>':''}`;$('[data-ta-close]').onclick=()=>$('#taBack').classList.remove('open');$('[data-ta-logout]').onclick=logout;try{const rows=await api('/api/team/members');renderMembers(rows)}catch(e){$('#taMembers').innerHTML=`<div class="ta-note" style="margin-top:12px">${esc(friendly(e)||'你可以正常使用日常业务，但没有成员管理权限。')}</div>`}if(canManageCompanies())loadOrganizations()}
function renderMembers(rows){const admin=['owner','admin'].includes(me?.role);$('#taMembers').innerHTML=`<h3>成员</h3>${admin?`<div class="ta-grid" style="margin-top:10px"><div class="ta-field"><label>姓名</label><input id="taNewName"></div><div class="ta-field"><label>邮箱</label><input id="taNewEmail" type="email"></div><div class="ta-field"><label>角色</label><select id="taNewRole"><option value="sales">业务员</option><option value="viewer">只读成员</option><option value="admin">管理员</option>${me.role==='owner'?'<option value="owner">老板</option>':''}</select></div><div class="ta-field"><label>初始密码</label><input id="taNewPassword" type="password" minlength="8"></div></div><div class="ta-row"><button class="ta-primary" data-ta-add>添加成员</button></div>`:''}<div class="ta-list">${rows.map(x=>`<div class="ta-item"><div><b>${esc(x.display_name||x.email)}</b><span>${esc(x.email)}${x.enabled?'':' · 已停用'}</span></div><div class="ta-row" style="margin:0"><span class="ta-role">${esc(roleName(x.role))}</span>${admin&&x.id!==me.id?`<button class="ta-btn" data-ta-toggle="${x.id}" data-enabled="${x.enabled?'1':'0'}">${x.enabled?'停用':'启用'}</button>`:''}</div></div>`).join('')}</div>`;$('[data-ta-add]')?.addEventListener('click',addMember);document.querySelectorAll('[data-ta-toggle]').forEach(b=>b.onclick=()=>toggleMember(b))}
async function addMember(){const payload={display_name:$('#taNewName').value,email:$('#taNewEmail').value,role:$('#taNewRole').value,password:$('#taNewPassword').value};if(!payload.email||payload.password.length<8)return alert('请填写成员邮箱，初始密码至少 8 位');try{await api('/api/team/members',{method:'POST',body:JSON.stringify(payload)});openTeam()}catch(e){alert(friendly(e))}}
async function toggleMember(btn){try{await api('/api/team/members/'+btn.dataset.taToggle,{method:'PATCH',body:JSON.stringify({enabled:btn.dataset.enabled!=='1'})});openTeam()}catch(e){alert(friendly(e))}}
async function loadOrganizations(){const box=$('#taOrganizations');if(!box)return;try{const rows=await api('/api/organizations');renderOrganizations(rows)}catch(e){box.innerHTML=`<div class="ta-note" style="margin-top:14px">${esc(friendly(e))}</div>`}}
function renderOrganizations(rows){const box=$('#taOrganizations');if(!box)return;box.innerHTML=`<div class="ta-divider"></div><h3>公司账号</h3><p>只有 HUIDI 管理账号可以看到这里。新建公司后，对方公司的客户、邮件、产品和业务会单独保存。</p><div class="ta-grid"><div class="ta-field"><label>公司名称</label><input id="taOrgName"></div><div class="ta-field"><label>负责人姓名</label><input id="taOrgOwnerName"></div><div class="ta-field"><label>负责人邮箱</label><input id="taOrgOwnerEmail" type="email"></div><div class="ta-field"><label>初始密码</label><input id="taOrgOwnerPassword" type="password" minlength="8"></div></div><div class="ta-row"><button class="ta-primary" data-ta-org-add>新建公司账号</button></div><div class="ta-list">${rows.map(x=>`<div class="ta-item"><div><b>${esc(x.name)}</b><span>${x.id===1?'当前公司':'独立公司账号'}${x.enabled?'':' · 已停用'}</span></div>${x.id!==1?`<button class="ta-btn" data-ta-org-toggle="${x.id}" data-enabled="${x.enabled?'1':'0'}">${x.enabled?'停用':'启用'}</button>`:''}</div>`).join('')}</div>`;$('[data-ta-org-add]')?.addEventListener('click',createOrganization);document.querySelectorAll('[data-ta-org-toggle]').forEach(b=>b.onclick=()=>toggleOrganization(b))}
async function createOrganization(){const payload={name:$('#taOrgName').value,owner_name:$('#taOrgOwnerName').value,owner_email:$('#taOrgOwnerEmail').value,owner_password:$('#taOrgOwnerPassword').value};if(!payload.name||!payload.owner_email||payload.owner_password.length<8)return alert('请填写公司名称、负责人邮箱，初始密码至少 8 位');try{await api('/api/organizations',{method:'POST',body:JSON.stringify(payload)});await loadOrganizations()}catch(e){alert(friendly(e))}}
async function toggleOrganization(btn){try{await api('/api/organizations/'+btn.dataset.taOrgToggle,{method:'PATCH',body:JSON.stringify({enabled:btn.dataset.enabled!=='1'})});await loadOrganizations()}catch(e){alert(friendly(e))}}
async function boot(){css();shell();ensureTop();try{status=await api('/api/team/status')}catch(_){status={enabled:false}}if(status.enabled){try{const out=await api('/api/team/me');me=out.member;organization=out.organization||out.member?.organization||null}catch(_){me=null;organization=null}topText();if(!me)openLogin()}else topText()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.HUIDITeamAccess=Object.freeze({open:openTeam});
})();